var dusk={},duskWolf={};dusk.warn=function(a){2<=this.logLevel&&console.warn(a);2<=this.htmlLogLevel&&this.logElem&&$("#"+this.logElem).append("<div style='color:#999900'>"+a+"</div>")};dusk.info=function(a){3<=this.logLevel&&console.info(a);3<=this.htmlLogLevel&&this.logElem&&$("#"+this.logElem).append("<div style='color:#000099'>"+a+"</div>")};dusk.log=function(a){4<=this.logLevel&&console.log(a);4<=this.htmlLogLevel&&this.logElem&&$("#"+this.logElem).append("<div style='color:#999999'>"+a+"</div>")};
dusk.logLevel="__logLevel__"in window?window.__logLevel__:4;dusk.htmlLogLevel="__htmlLogLevel__"in window?window.__htmlLogLevel__:4;dusk.ver="0.0.10-alpha";dusk.verId=10;dusk.frameRate="__frameRate__"in window?window.__frameRate__:60;dusk.canvas="__canvas__"in window?window.__canvas__:"canvas";dusk.logElem="__logElement__"in window?window.__logElement__:"dwlog";dusk.dev="__development__"in window?window.__development__:!0;dusk.startGame=function(){setTimeout(dusk.startGame,100)};window.duskWolf=dusk;
window.duskWolf.error=function(a){1<=this.logLevel&&window.console.error(a);1<=this.htmlLogLevel&&this.logElem&&$("#"+this.logElem).append("<div style='color:#990000'>"+a+"</div>")};dusk.data={};dusk.data.init=function(){dusk.data._loaded={};dusk.data.scripts=[];dusk.data._hold="";dusk.data.root=dusk.data.grabJson("root");$.ajaxSetup({cache:!dusk.dev});if(dusk.data.root)if(dusk.data.root.duskVer>dusk.verId)dusk.error("DuskWolf version is incompatable with this program.");else return dusk.info(dusk.data.root.name+" is loading."),dusk.data;else dusk.error("Root json could not be loaded.")};
dusk.data.download=function(a,b,c){void 0===this._loaded[a]&&(console.log("Downloading file "+a+"..."),$.ajax({async:c,dataType:void 0!==b?b:"text",error:function(b,c,f){console.error("Error getting "+a+", "+f);dusk.data._hold=""},success:function(a){dusk.data._hold=a},url:__datadir__+"/"+a}),this._loaded[a]=dusk.data._hold);return this._loaded[a]};
dusk.data.grabJson=function(a,b){-1===a.indexOf(".")&&(a+=".json");if(a.match(/\.dws$/i)&&b)return this.grabDws(a);var c=dusk.data.download(a,"text",!1).replace(/\t/g," ").replace(/\/\*(?:.|\n)*?\*\//g,"").replace(/\n/g," ");if(this._isJson(c))return window.JSON.parse(c);if(b)return this.grabDws(a)};
dusk.data.grabDws=function(a){-1===a.indexOf(".")&&(a+=".dws");var b=dusk.data.download(a,"text",!1);try{return window.JSON.parse(dusk.dwc.compile(b))}catch(c){return console.error("Could not parse "+a+" as DWS."),console.error(c.name+", "+c.description),{}}};dusk.data.grabImage=function(a){void 0===this._loaded[a]&&(console.log("Downloading image "+a+"..."),this._loaded[a]=new Image,this._loaded[a].src=__datadir__+"/"+a);return this._loaded[a]};
dusk.data._isJson=function(a){return/^[\],:{}\s]*$/.test(String(a).replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))};dusk.dwc={};dusk.dwc.bOpen="\"'([{<";dusk.dwc.bClose="\"')]}>";dusk.dwc.lang={};dusk.dwc.addLangDef=function(a,b){dusk.dwc.lang[a]=b};
dusk.dwc.compile=function(a){for(var b="",c=0,d=!0;a[c];){var c=dusk.dwc.ignoreWhitespace(a,c),e=dusk.dwc.read(a,c,/[\s\n\;]/)[0],c=dusk.dwc.read(a,c,/[\s\n\;]/)[1];if(!e)break;if(!dusk.dwc.lang[e])throw Error("Unrecognised action '"+e+"'.");d||(b+=",");for(var b=b+('{"a":'+dusk.dwc.cast(e,"STR")),d=!1,f=0;";"!=a[c]&&a[c];){var c=dusk.dwc.ignoreWhitespace(a,c),g=void 0,h=dusk.dwc.read(a,c,/[\s\n\:\;]/)[0],c=dusk.dwc.read(a,c,/[\s\n\:\;]/)[1];":"==a[c]&&(c++,g=h,h=dusk.dwc.read(a,c,/[\s\n\:\;]/)[0],
c=dusk.dwc.read(a,c,/[\s\n\:\;]/)[1]);if(dusk.dwc.lang[e][f]&&(void 0===g||g==dusk.dwc.lang[e][f][0]))g=dusk.dwc.lang[e][f][0],f++;if(!g)throw Error("Unknown property for "+e+" encountered.");for(var b=b+(","+dusk.dwc.cast(g,"STR")+":"),i=dusk.dwc.lang[e].length-1;;i--){if(0>i){b+=dusk.dwc.cast(h,"STR");break}if(dusk.dwc.lang[e][i][0]===g){b+=dusk.dwc.cast(h,dusk.dwc.lang[e][i][2]);break}}";"!=a[c]&&c++;c=dusk.dwc.ignoreWhitespace(a,c)}b+="}";c++}return"["+b+"]"};
dusk.dwc.cast=function(a,b){var c=dusk.dwc.removeBlock(a),b=b.split(":");if("null"==c||void 0===c)return"null";switch(b[0]){default:case "STR":return'"'+c.replace('"','\\"')+'"';case "NUM":return isNaN(c)?dusk.dwc.cast(c,"STR"):Number(c);case "DWC":return dusk.dwc.compile(c);case "BLN":return"false"!==c;case "OBJ":return a;case "ARR":if(1>b.length)throw Error("No type for array element!");var d="[",e=0,f=!1;for(b.splice(0,1);c[e];){var g=dusk.dwc.read(c,e,/[\s\n\:\;]/)[0],e=dusk.dwc.read(c,e,/[\s\n\:\;]/)[1]+
1;f&&(d+=",");f=!0;d+=dusk.dwc.cast(g,b.join(":"));e=dusk.dwc.ignoreWhitespace(c,e)}return d+"]"}};dusk.dwc.ignoreWhitespace=function(a,b){for(var c="",d=!1;c=a[b];){"/"==c&&"*"==a[b+1]&&(d=!0);if("/"==c&&"*"==a[b-1])d=!1;else if(!d&&!a[b].match(/[\s\n]/))break;b++}return b};
dusk.dwc.read=function(a,b,c,d){var e=a[b],f="",g=["\x00",1],h=["\x00",0],i=!1;-1!==dusk.dwc.bOpen.indexOf(a[b])&&(g[0]=a[b],h[0]=dusk.dwc.bClose[dusk.dwc.bOpen.indexOf(a[b])]);for(b++;f=a[b];){"/"==f&&("*"==a[b+1]&&"\x00"==g[0])&&(i=!0);if("/"==f&&"*"==a[b-1]&&"\x00"==g[0])i=!1;else if(!i){e+=f;f==h[0]&&h[1]++;f==g[0]&&f!=h[0]&&g[1]++;if(h[1]==g[1])break;if(c&&f.match(c)&&"\x00"==g[0]&&"\x00"==h[0]){if(!d||d&&!f.match(d))e=e.substr(0,e.length-1);break}}b++}return[e,b]};
dusk.dwc.removeBlock=function(a){return!a?a:-1!==dusk.dwc.bOpen.indexOf(a[0])&&a[a.length-1]==dusk.dwc.bClose[dusk.dwc.bOpen.indexOf(a[0])]?a.substr(1,a.length-2):a};dusk.dwc._isJson=function(a){return/^[\],:{}\s]*$/.test(String(a).replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))};dusk.errors={};dusk.errors.PropertyMissing=function(a,b){this.name="DuskPropertyMissingError";this.action=a;this.property=b;this.message="Action "+a+" is missing property "+b};dusk.errors.PropertyMissing.prototype=Error();dusk.errors.PropertyMissing.prototype.constructor=dusk.errors.PropertyMissing;dusk.errors.ArgLengthWrong=function(a,b,c){this.name="DuskArgLengthWrongError";this.hash=a;this.length=b;this.expected=c;this.message="Hashfunction expected at least "+c+" args, but only got "+b};
dusk.errors.ArgLengthWrong.prototype=Error();dusk.errors.ArgLengthWrong.prototype.constructor=dusk.errors.ArgLengthWrong;dusk.events={};
dusk.events.init=function(){dusk.events._game=dusk.game;dusk.events._actions={};dusk.events._hashFuncts={};dusk.events._functions={};dusk.events._listeners=[];dusk.events._vars={};dusk.events._threads={};dusk.events._frameHandlers={};dusk.events._keyHandlers={};dusk.events._keyUpHandlers={};dusk.events._startHandlers=[];dusk.events._modsInited={};dusk.events._ops="* / + - < > <= >= = != && ||".split(" ");dusk.events._opsReg=[];for(var a=0;a<dusk.events._ops.length;a++)dusk.events._opsReg[a]=RegExp("([^"+
dusk.events._regEscape(dusk.events._ops.join(""))+"]+)\\s*("+dusk.events._regEscape(dusk.events._ops[a])+")\\s*([^"+dusk.events._regEscape(dusk.events._ops.join(""))+"]+)","i");dusk.events.thread="";dusk.events.setVar("sys.game.ver",dusk.ver);dusk.events.setVar("sys.game.verid",dusk.verId);dusk.events.setVar("sys.game.frameRate",dusk.frameRate);dusk.events.registerAction("comment",function(){},dusk.events,[["",!1,"STR"]]);dusk.events.registerAction("function",dusk.events._addFunction,dusk.events,
[["name",!0,"STR"],["actions",!0,"DWC"]]);dusk.events.registerAction("listen",dusk.events._addListener,dusk.events,[["event",!0,"STR"],["actions",!0,"DWC"],["name",!1,"STR"]]);dusk.events.registerAction("if",dusk.events._iffy,dusk.events,[["cond",!0,"STR"],["then",!1,"DWC"],["else",!1,"DWC"]]);dusk.events.registerAction("ifset",dusk.events._ifset,dusk.events);dusk.events.registerAction("while",dusk.events._whiley,dusk.events,[["cond",!0,"STR"],["actions",!0,"DWC"]]);dusk.events.registerAction("call",
dusk.events._callFunction,dusk.events,[["name",!0,"STR"],["thread",!1,"STR"]]);dusk.events.registerAction("fire",dusk.events._fire,dusk.events,[["event",!0,"STR"]]);dusk.events.registerAction("unlisten",dusk.events._unlisten,dusk.events,[["name",!1,"STR"],["event",!1,"STR"]]);dusk.events.registerAction("var",dusk.events._setVarInternal,dusk.events,[["name",!0,"STR"],["value",!0,"OBJ"],["inherit",!1,"STR"]]);dusk.events.registerAction("delvar",dusk.events._delVarInternal,dusk.events,[["name",!0,"STR"]]);
dusk.events.registerAction("thread",dusk.events._threadTo,dusk.events,[["name",!0,"STR"],["actions",!0,"DWC"]]);dusk.events.registerAction("vardump",function(){console.log(dusk.events._vars)},dusk.events,[]);dusk.events.registerHashFunct("IF",dusk.events._hiffy,dusk.events);dusk.events.registerHashFunct("=",dusk.events._rawCond,dusk.events);return dusk.events};
dusk.events.startGame=function(){for(var a=0;a<this._startHandlers.length;a++)this._startHandlers[a][0].call(this._startHandlers[a][1]);for(a=dusk.data.root.files.length-1;0<=a;a--)(dusk.data.grabJson(dusk.data.root.files[a]),!0)&&this.run(dusk.data.grabJson(dusk.data.root.files[a],!0),"_init")};
dusk.events.everyFrame=function(){this.getVar("sys.started")&&this.run([{a:"fire",event:"sys-event-frame"}],"_frame");for(var a in this._frameHandlers)this._frameHandlers[a][0].call(this._frameHandlers[a][1]);for(var b=200;0<b;b--){a=!1;for(var c in this._threads)a=this.next(c,!1)?!0:a;if(!a)break}};dusk.events.keypress=function(a){for(var b in this._keyHandlers)this._keyHandlers[b][0].call(this._keyHandlers[b][1],a)};
dusk.events.keyup=function(a){for(var b in this._keyUpHandlers)this._keyUpHandlers[b][0].call(this._keyUpHandlers[b][1],a)};dusk.events.run=function(a,b){b||(b="main");"string"==typeof a&&(a=JSON.parse(a));for(var c=0;c<a.length;c++)this._getThread(b,!0).buffer[this._getThread(b,!0).buffer.length]=a[c]};
dusk.events.next=function(a,b){void 0===b&&(b=!0);b&&this._getThread(a).nexts--;if(0<this._getThread(a).nexts)return!1;this._getThread(a).nexts=0;for(var c=this._getThread(a).buffer.length-1;0<=c;c--)this._getThread(a).stack[this._getThread(a).stack.length]=this._getThread(a).buffer[c];this._getThread(a).buffer=[];if(0==this._getThread(a).stack.length)return!1;c=this._clone(this._getThread(a).stack.pop());if("string"==typeof c)return!0;"while"!=c.a&&(c=this.replaceVar(c));if(this._actions[c.a])return this.thread=
a,this._actions[c.a][0].call(this._actions[c.a][1],c),!0;console.error('Unknown action "'+c.a+'".');console.log(c);return!0};dusk.events._clone=function(a){if(null==a||"object"!=typeof a)return a;var b=a.constructor(),c;for(c in a)b[c]=this._clone(a[c]);return b};dusk.events.awaitNext=function(a,b){void 0===a&&(a=this.thread);void 0===b&&(b=1);this._getThread(a).nexts+=b;return a};
dusk.events.replaceVar=function(a,b){for(var c in a)if("string"==typeof a[c])a[c]=this.parseVar(a[c]);else if(b&&"array"==typeof a[c])for(var d=a[c].length-1;0<=d;d--)a[c][d]=this.replaceVar(a[c][d],!1);return a};dusk.events.hashFunction=function(a,b){return!this._hashFuncts[a.toLowerCase()]?(duskWolf.warn("No hashfunction named #"+a+"."),""):this._hashFuncts[a.toLowerCase()][0].call(this._hashFuncts[a.toLowerCase()][1],a,b)};
dusk.events.registerAction=function(a,b,c,d){dusk.dwc.addLangDef(a,d);this._actions[a]=[b,c]};dusk.events.registerHashFunct=function(a,b,c){this._hashFuncts[a.toLowerCase()]=[b,c]};dusk.events.registerFrameHandler=function(a,b,c){this._frameHandlers[a]=[b,c]};dusk.events.registerKeyHandler=function(a,b,c){this._keyHandlers[a]=[b,c]};dusk.events.registerKeyUpHandler=function(a,b,c){this._keyUpHandlers[a]=[b,c]};
dusk.events.registerStartHandler=function(a,b){this._startHandlers[this._startHandlers.length]=[a,b]};dusk.events._addFunction=function(a){if(!a.name)throw new dusk.errors.PropertyMissing(a.a,"name");if(!a.actions)throw new dusk.errors.PropertyMissing(a.a,"actions");this._functions[a.name]=a.actions};
dusk.events._callFunction=function(a){if(!a.name)throw new dusk.errors.PropertyMissing(a.a,"name");this._functions[a.name]?this.run(this._functions[a.name],a.thread?a.thread:this.thread):duskWolf.error("Function "+a.name+" does not exist!")};dusk.events._threadTo=function(a){if(!a.name)throw new dusk.errors.PropertyMissing(a.a,"name");if(!a.actions)throw new dusk.errors.PropertyMissing(a.a,"actions");this.run(a.actions,a.name)};
dusk.events._getThread=function(a,b){if(this._threads[a])return this._threads[a];if(b)return this._threads[a]={},this._threads[a].stack=[],this._threads[a].buffer=[],this._threads[a].nexts=0,this._threads[a];duskWolf.error("Thread "+a+" does not exist!");return null};
dusk.events._addListener=function(a){if(!a.event)throw new dusk.errors.PropertyMissing(a.a,"event");if(a.name)for(var b in this._listeners)if(this._listeners[b].name&&this._listeners[b].name==a.name)return;this._listeners[this._listeners.length]=a};
dusk.events._unlisten=function(a){for(var b=this._listeners.length-1;0<=b;b--)if(this._listeners[b]&&this._listeners[b].event==a.event){var c=!1,d;for(d in this._listeners[b])if(-1==["actions","event","__proto__","a"].indexOf(d)&&a[d]&&(this._listeners[b][d]!=a[d]&&"!"!=this._listeners[b][d][0]||"!"+this._listeners[b][d]==a[d]&&"!"==this._listeners[b][d][0])){c=!0;break}c||delete this._listeners[b]}};
dusk.events._fire=function(a){if(!a.event)throw new dusk.errors.PropertyMissing(a.a,"event");for(var b=this._listeners.length-1;0<=b;b--)if(this._listeners[b]&&this._listeners[b].event==a.event){var c=!1,d;for(d in this._listeners[b])if(-1==["name","actions","event","__proto__","a"].indexOf(d)&&this._listeners[b][d]&&(this._listeners[b][d]!=a[d]&&"!"!=this._listeners[b][d][0]||"!"+this._listeners[b][d]==a[d]&&"!"==this._listeners[b][d][0])){c=!0;break}c||this.run(this._listeners[b].actions,this.thread)}};
dusk.events._iffy=function(a){if(void 0===a.cond)throw new dusk.errors.PropertyMissing(a.a,"cond");this.cond(a.cond)?void 0!==a.then&&this.run(a.then,this.thread):void 0!==a["else"]&&this.run(a["else"],this.thread)};dusk.events._hiffy=function(a,b){if(void 0===b[0])duskWolf.error("No condition for #IF.");else{if(this.cond(b[0])){if(void 0!==b[1])return b[1]}else if(void 0!==b[2])return b[2];return""}};dusk.events._rawCond=function(a,b){return this.cond(b[0])};
dusk.events._ifSet=function(a){if(!("value"in a))throw new dusk.errors.PropertyMissing(a.a,"value");a.value?"else"in a&&this.run(a["else"],this.thread):"then"in a&&this.run(a.then,this.thread)};
dusk.events._whiley=function(a){if(!a.cond)throw new dusk.errors.PropertyMissing(a.a,"cond");if(!a.actions)throw new dusk.errors.PropertyMissing(a.a,"actions");if(this.cond(this.parseVar(a.cond))){var b=(new Date).getTime();a.actions[a.actions.length]={a:"if",cond:a.cond,then:[{a:"call",name:"_while_"+b}]};this.run([{a:"function",name:"_while_"+b,actions:a.actions},{a:"call",name:"_while_"+b}],this.thread)}};
dusk.events._isJson=function(a){return/^[\],:{}\s]*$/.test(String(a).replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))};dusk.events._regEscape=function(a){return a.replace(/[-[\]{}()*+?.,\\^$|#\s]/g,"\\$&")};
dusk.events.parseVar=function(a,b){for(var a=String(a),c=null,d=!0;d;){for(d=!1;c=/\$([-\.a-zA-Z0-9]+);?/gi.exec(a);)d=!0,a=a.replace(c[0],this.getVar(c[1]));for(;c=/\$-([-\.a-zA-Z0-9]+);?/gi.exec(a);)d=!0,a=a.replace(c[0],-1*this.getVar(c[1]));for(;c=/#([^#\(]+)\(([^;#\$]+)\);?/gi.exec(a);)d=!0,a=a.replace(c[0],this.hashFunction(c[1],c[2].split(",")))}return!b&&this._isJson(a)?JSON.parse(a):a};
dusk.events.cond=function(a,b){for(var a=String(a),c;c=/\((.*?)\)/.exec(a);)a=a.replace(c[0],this.cond(c[1],!0));for(var d=0;d<this._ops.length;d++)for(;c=this._opsReg[d].exec(a);)a=a.replace(c[0],this._doOp(c[1],c[3],c[2]));return!b&&this._isJson(a)?JSON.parse(a):a};
dusk.events._doOp=function(a,b,c){a=this.cond(a);b&&(b=this.cond(b));switch(c){case "+":return a+b;case "-":return a-b;case "*":return a*b;case "/":return a/b;case "=":return a==b;case "!=":return a!=b;case "<":return a<b;case ">":return a>b;case ">=":return a>=b;case "<=":return a>=b;case "&&":return Boolean(a)&&Boolean(b);case "||":return Boolean(a)||Boolean(b)}};
dusk.events._setVarInternal=function(a){if(void 0===a.name)throw new dusk.errors.PropertyMissing(a.a,"name");if(void 0===a.value)throw new dusk.errors.PropertyMissing(a.a,"value");this.setVar(a.name,a.value,a.inherit)};
dusk.events.setVar=function(a,b,c){a=String(a);-1!=a.indexOf(",")&&duskWolf.warning("setVar","A variable name with a comma in it may cause problems.");var a=a.toLowerCase(),a=a.split("."),d=this._vars;if(1<a.length)for(var e=0;e<a.length-1;e++)void 0===d[a[e]]&&(d[a[e]]={}),d=d[a[e]];if(void 0!==c){d[a[a.length-1]]=this._clone(this.getVar(c));for(var f in b)d[a[a.length-1]][f]=b[f];return b}return d[a[a.length-1]]=b};
dusk.events.setVars=function(a){for(var b=a.length-1;0<=b;b--)this.setVar(a[b][0],a[b][1])};dusk.events.getVar=function(a){var a=a.toLowerCase(),a=a.split("."),b=this._vars;if(1<a.length)for(var c=0;c<a.length-1;c++){if(void 0===b[a[c]])return;b=b[a[c]]}if(void 0!==b[a[a.length-1]])return b[a[a.length-1]]};dusk.events.getVars=function(a){var b=[],c;for(c in this._vars)a.test(c)&&(b[b.length]=[c,this._vars[c]]);return b};
dusk.events._delVarInternal=function(a){if(!a.name)throw new dusk.errors.PropertyMissing(a.a,"name");this.delVar(a.name)};dusk.events.delVar=function(a){var a=a.toLowerCase(),a=a.split("."),b=this._vars;if(1<a.length)for(var c=0;c<a.length-1;c++){if(void 0===b[a[c]])return;b=b[a[c]]}void 0!==b[a[a.length-1]]&&delete b[a[a.length-1]]};dusk.game={};
dusk.game.init=function(){console.log("DuskWolf ver "+duskWolf.ver+" is starting.");this._framesRan=0;this._time=(new Date).getTime();this._crashed=!1;this._counter=0;window.events=dusk.events.init();dusk.data.init();window.mods={};for(var a=[],b=dusk.data.root.mods.length-1;0<=b;b--)console.log("Loading mod "+dusk.data.root.mods[b]+"..."),a.push("dusk.mods."+dusk.data.root.mods[b]);for(b=dusk.data.root.coms.length-1;0<=b;b--)console.log("Loading component "+dusk.data.root.coms[b]+"..."),a.push("dusk.sgui."+
dusk.data.root.coms[b]);for(b=dusk.data.root.reqs.length-1;0<=b;b--)console.log("Loading other file "+dusk.data.root.reqs[b]+"..."),a.push(dusk.data.root.reqs[b]);(window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame)(this.onRender);setInterval(this.everyFrame,1E3/dusk.frameRate);if(dusk.dev){var c="java -jar $closureLocation --js `find *.js */*.js` --compilation_level SIMPLE_OPTIMIZATIONS --js_output_file DWCompiled.js --language_in ECMASCRIPT5 --manage_closure_dependencies --closure_entry_point dusk.load --closure_entry_point dusk.gameStarter";
for(b in a)c+=" --closure_entry_point "+a[b];console.log("----- Compiler command -----");console.log(c);console.log("----- Compiler command -----")}"goog"in window&&goog.require.call(this,"dusk.gameStarter");return dusk.game};dusk.game.onRender=function(){dusk.mods&&dusk.mods.simpleGui&&dusk.mods.simpleGui.draw();(window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame)(dusk.game.onRender)};
dusk.game.everyFrame=function(){try{for(dusk.game._counter+=duskWolf.frameRate/60;1<dusk.game._counter;)dusk.game._counter--,dusk.events.everyFrame(),dusk.dev&&(dusk.game._framesRan++,100==dusk.game._framesRan&&(console.log("100 frames took "+((new Date).getTime()-dusk.game._time)+"ms, "+Math.round(1E8/((new Date).getTime()-dusk.game._time))/1E3+"fps."),dusk.game._time=(new Date).getTime(),dusk.game._framesRan=0))}catch(a){console.log("Error! "+a.name+", "+a.message)}};dusk.game.keypress=function(a){dusk.events.keypress(a)};
dusk.game.keyup=function(a){dusk.events.keyup(a)};dusk.load={};var __duskdir__=__duskdir__?__duskdir__:"DuskWolf",__datadir__=__datadir__?__datadir__:"Data",log=!0,logDiv="info",loaded=[];
function __import__(a){if(-1==loaded.indexOf(a)){$.ajaxSetup({async:!1});if("string"==typeof a)log&&console.log("Importing "+a+" from "+__duskdir__+"/"+a+"..."),logDiv&&$("#"+logDiv).append("<b>Importing</b> "+a+"...<br/>"),$("head").append("<script type='text/javascript' src='"+__duskdir__+"/"+a+"'><\/script>");else for(var b=0;b<a.length;b++)__import__(a[b]);$.ajaxSetup({async:!0});loaded[loaded.length]=a}}document.onkeydown=function(a){if(37<=a.keyCode&&40>=a.keyCode)return!1};
try{window.game=dusk.game.init()}catch(e$$17){duskWolf.error(e$$17)}$(document).bind("keydown",function(a){try{"game"in window&&dusk.game.keypress(a)}catch(b){console.error(b.name+", "+b.message)}});$(document).bind("keyup",function(a){try{"game"in window&&dusk.game.keyup(a)}catch(b){console.error(b.name+", "+b.message)}});dusk.gameStarter={};dusk.startGame=function(){dusk.events.startGame();dusk.events.run([{a:"fire",ver:dusk.ver,"ver-id":dusk.verId,event:"sys-event-load"},{a:"fire",ver:dusk.ver,"ver-id":dusk.verId,event:"sys-event-start"},{a:"var",name:"sys.started",value:!0}],"_init")};dusk.mods={};dusk.mods.core={};
dusk.mods.core.init=function(){dusk.events.registerAction("print",function(a){console.log(a.text);return!0},this,[["text",!0,"STR"]]);dusk.events.registerAction("error",function(a){console.error(a.text);return!0},this,[["text",!0,"STR"]]);dusk.events.registerAction("warn",function(a){console.warn(a.text);return!0},this,[["text",!0,"STR"]]);dusk.events.registerAction("inc",this._increment,this,[["var",!0,"STR"],["by",!1,"NUM"]]);dusk.events.registerAction("mul",this._multiply,this,[["var",!0,"STR"],
["by",!1,"NUM"]]);dusk.events.registerAction("div",this._divide,this,[["var",!0,"STR"],["by",!1,"NUM"]]);dusk.events.registerAction("modulo",this._modulo,this,[["var",!0,"STR"],["by",!1,"NUM"]]);dusk.events.registerHashFunct("/",this._div,this);dusk.events.registerHashFunct("%",this._mod,this);dusk.events.registerHashFunct("+",this._sum,this);dusk.events.registerHashFunct("*",this._prod,this)};
dusk.mods.core._increment=function(a){if(void 0===a["var"])throw new dusk.errors.PropertyMissing(a.a,"var");void 0===a.by&&(a.by=1);dusk.events.setVar(a["var"],Number(dusk.events.getVar(a["var"]))+Number(a.by))};dusk.mods.core._multiply=function(a){if(void 0===a["var"])throw new dusk.errors.PropertyMissing(a.a,"var");void 0===a.by&&(a.by=2);dusk.events.setVar(a["var"],Number(dusk.events.getVar(a["var"]))*Number(a.by))};
dusk.mods.core._modulo=function(a){if(void 0===a["var"])throw new dusk.errors.PropertyMissing(a.a,"var");void 0===a.by&&(a.by=10);dusk.events.setVar(a["var"],Number(dusk.events.getVar(a["var"]))%Number(a.by))};dusk.mods.core._sum=function(a,b){if(1>b.length)throw new dusk.errors.ArgLengthWrong(a,b.length,1);for(var c=0,d=b.length-1;0<=d;d--)c+=Number(b[d]);return c};
dusk.mods.core._prod=function(a,b){if(1>b.length)throw new dusk.errors.ArgLengthWrong(a,b.length,1);for(var c=1,d=b.length-1;0<=d;d--)c*=Number(b[d]);return c};dusk.mods.core._div=function(a,b){if(void 0===b[0])throw new dusk.errors.ArgLengthWrong(a,b.length,1);void 0===b[1]&&(b[1]=2);return Number(b[0])/Number(b[1])};dusk.mods.core._mod=function(a,b){if(void 0===b[0])throw new dusk.errors.ArgLengthWrong(a,b.length,1);void 0===b[1]&&(b[1]=10);return Number(b[0])%Number(b[1])};dusk.mods.core.init();dusk.mods.keyboard={};
dusk.mods.keyboard.init=function(){dusk.events.registerKeyHandler("KeyboardKey",this._handleKeypress,this);dusk.events.registerKeyUpHandler("KeyboardUpKey",this._handleKeyup,this);this._keys={};this._codes={8:["BACKSPACE",!1],9:["TAB",!1],13:["ENTER",!1],32:[" ",!0],37:["LEFT",!1],38:["UP",!1],39:["RIGHT",!1],40:["DOWN",!1],48:["0",!0],49:["1",!0],50:["2",!0],51:["3",!0],52:["4",!0],53:["5",!0],54:["6",!0],55:["7",!0],56:["8",!0],57:["9",!0],65:["a",!0],66:["b",!0],67:["c",!0],68:["d",!0],69:["e",
!0],70:["f",!0],71:["g",!0],72:["h",!0],73:["i",!0],74:["j",!0],75:["k",!0],76:["l",!0],77:["m",!0],78:["n",!0],79:["o",!0],80:["p",!0],81:["q",!0],82:["r",!0],83:["s",!0],84:["t",!0],85:["u",!0],86:["v",!0],87:["w",!0],88:["x",!0],89:["y",!0],90:["z",!0]};dusk.events.registerAction("if-key",this._ifkey,this,[["key",!0,"NUM"],["then",!1,"DWC"],["else",!1,"DWC"]]);dusk.events.registerHashFunct("KCODE",this._keyCode,this);dusk.events.registerHashFunct("CKEY",this._codeKey,this)};
dusk.mods.keyboard.addActions=function(){};dusk.mods.keyboard._handleKeypress=function(a){dusk.events.run([{a:"fire",key:a.keyCode,shift:a.shiftKey,ctrl:a.ctrlKey,alt:a.altKey,event:"key-event-down"}],"_keyboard");this._keys[a.keyCode]=!0};dusk.mods.keyboard._handleKeyup=function(a){dusk.events.run([{a:"fire",key:a.keyCode,shift:a.shiftKey,ctrl:a.ctrlKey,alt:a.altKey,event:"key-event-up"}],"_keyboard");this._keys[a.keyCode]=!1};
dusk.mods.keyboard.isKeyPressed=function(a){return!(a in this._keys)?!1:this._keys[a]};dusk.mods.keyboard.lookupCode=function(a){return!(a in this._codes)?["UNKNOWN",!1]:this._codes[a]};dusk.mods.keyboard._ifKey=function(a){if(!a.key)throw new dusk.errors.PropertyMissing(a.a,"key");this.isKeyPressed(a.key)?"then"in a&&this.run(a.then,this._events.thread):"else"in a&&this.run(a["else"],this._events.thread)};
dusk.mods.keyboard._keyCode=function(a,b){if(!b.length)throw new dusk.errors.ArgLengthWrong(a,b.length,1);for(var c in this._codes)if(this._codes[c][0].toUpperCase()==b[0].toUpperCase())return c;return-1};dusk.mods.keyboard._codeKey=function(a,b){if(!b.length)throw new dusk.errors.ArgLengthWrong(a,b.length,1);return void 0!==this._codes[b[0]]?this._codes[b[0]][0]:""};dusk.mods.keyboard.init();dusk.mods.localSaver={};dusk.mods.localSaver.init=function(){dusk.events.registerAction("local-save",this._save,this,[["name",!0,"STR"],["vars",!0,"ARR:STR"],["regexp",!1,"BLN"]]);dusk.events.registerAction("local-load",this._load,this,[["name",!0,"STR"]]);dusk.events.registerAction("local-clear",this._clear,this,[["name",!0,"STR"]])};
dusk.mods.localSaver._save=function(a){if(!("name"in a))throw new dusk.errors.PropertyMissing(a.a,"name");if(!("vars"in a))throw new dusk.errors.PropertyMissing(a.a,"vars");if("regexp"in a&&"1"==a.regexp)if("array"==typeof a.vars){for(var b=[],c=a.vars.length-1;0<=c;c--)b=b.concat(this._events.getVars(RegExp(a.vars[c])));window.localStorage["dw_"+a.name]=JSON.stringify(b)}else window.localStorage["dw_"+a.name]=JSON.stringify(this._events.getVars(RegExp(a.vars)));else if("array"==typeof a.vars){b=
[];for(c=a.vars.length-1;0<=c;c--)b=b[b.length]=[a.vars[c],this._events.getVar(a.vars[c])];window.localStorage["dw_"+a.name]=JSON.stringify(b)}else window.localStorage["dw_"+a.name]=JSON.stringify([[a.vars,this._events.getVar(a.vars)]])};dusk.mods.localSaver._load=function(a){if(!("name"in a))throw new dusk.errors.PropertyMissing(a.a,"name");dusk.events.setVars(window.JSON.parse(window.localStorage["dw_"+a.name]))};
dusk.mods.localSaver._clear=function(a){if(!("name"in a))throw new dusk.errors.PropertyMissing(a.a,"name");delete window.localStorage["dw_"+a.name]};dusk.mods.localSaver.init();dusk.mods.math={};
dusk.mods.math.init=function(){dusk.events.registerHashFunct("SIN",this._trig,this);dusk.events.registerHashFunct("COS",this._trig,this);dusk.events.registerHashFunct("TAN",this._trig,this);dusk.events.registerHashFunct("ASIN",this._untrig,this);dusk.events.registerHashFunct("ACOS",this._untrig,this);dusk.events.registerHashFunct("ATAN",this._untrig,this);dusk.events.registerHashFunct("ROUND",this._round,this);dusk.events.setVar("math.pi",Math.PI);dusk.events.setVar("math.e",Math.E);dusk.events.setVar("math.phi",
1.61803398874989);dusk.events.setVar("math.infinity",Infinity)};dusk.mods.math._trig=function(a,b){if(1>b.length)dusk.error("No argument to trig function.");else{2<=b.length&&b[1]&&(b[0]=b[0]/180*Math.PI);var c=0;switch(a){case "sin":c=Math.sin(b[0]);break;case "cos":c=Math.cos(b[0]);break;case "tan":c=Math.tan(b[0]),c==Math.tan(Math.PI/2)&&(c=Infinity)}return Math.round(1E10*c)/1E10}};
dusk.mods.math._untrig=function(a,b){if(1>b.length)dusk.error("No argument to trig function.");else{var c=0;switch(a){case "asin":c=Math.asin(b[0]);break;case "acos":c=Math.acos(b[0]);break;case "atan":c=Math.atan(b[0])}c=Math.round(1E10*c)/1E10;return 2<=b.length&&b[1]?Math.round(c*(180/Math.PI)):c}};dusk.mods.math._round=function(a,b){var c=1;if(1>b.length)dusk.error("Nothing to round.");else return 2<=b.length&&b[1]&&(c=Math.pow(10,b[1])),Math.round(b[0]*c)/c};dusk.mods.math.init();dusk.mods.net={};dusk.mods.net.init=function(){dusk.events.registerAction("import",this._get,this,[["file",!0,"STR"],["thread",!1,"STR"]]);dusk.events.registerAction("fetch",this._get,this,[["file",!0,"STR"]]);dusk.events.registerHashFunct("FILE",this._file,this)};dusk.mods.net._get=function(a){if(!a.file)throw new dusk.errors.PropertyMissing(a.a,"file");"import"===a.a?dusk.events.run(dusk.data.grabJson(a.file,!0),a.thread?a.thread:dusk.events.thread):dusk.data.grabImage(a.file)};
dusk.mods.net._file=function(a,b){if(b[0])return dusk.data.download(b[0],b[1]);dusk.error("No file to retreive.")};dusk.mods.net.init();window.pbehave={};dusk.pbehave={};dusk.pbehave.PBehave={};dusk.pbehave.Stayer={};window.pbehave.PBehave=function(a,b){this._entity=a;this._events=b};window.pbehave.PBehave.prototype.everyFrame=function(){};window.pbehave.PBehave.prototype.onLand=function(){};window.pbehave.PBehave.prototype.onBonk=function(){};window.pbehave.PBehave.prototype.onHitRight=function(){};window.pbehave.PBehave.prototype.onHitLeft=function(){};window.pbehave.PBehave.prototype.onCollideLeft=function(){};
window.pbehave.PBehave.prototype.onCollideRight=function(){};window.pbehave.PBehave.prototype.onCollideTop=function(){};window.pbehave.PBehave.prototype.onCollideBottom=function(){};window.pbehave.Stayer=function(a,b){void 0!==a&&window.pbehave.PBehave.call(this,a,b)};window.pbehave.Stayer.prototype=new window.pbehave.PBehave;window.pbehave.Stayer.constructor=window.pbehave.Stayer;dusk.pbehave.BackForth={};window.pbehave.BackForth=function(a,b){void 0!==a&&(window.pbehave.PBehave.call(this,a,b),this._entity.dx=this._entity.eProp("haccel"))};window.pbehave.BackForth.prototype=new window.pbehave.PBehave;window.pbehave.BackForth.constructor=window.pbehave.BackForth;
window.pbehave.BackForth.prototype.everyFrame=function(){0>this._entity.dx&&this._entity.dx>-this._entity.eProp("hspeed")?this._entity.dx-=this._entity.eProp("haccel"):0<this._entity.dx&&this._entity.dx<this._entity.eProp("hspeed")&&(this._entity.dx+=this._entity.eProp("haccel"))};window.pbehave.BackForth.prototype.onHitLeft=function(){this._entity.dx=this._entity.eProp("haccel")};window.pbehave.BackForth.prototype.onHitRight=function(){this._entity.dx=-this._entity.eProp("haccel")};
window.pbehave.BackForth.prototype.onCollideLeft=function(){this._entity.dx=-this._entity.eProp("haccel")};window.pbehave.BackForth.prototype.onCollideRight=function(){this._entity.dx=this._entity.eProp("haccel")};dusk.pbehave.Controlled={};window.pbehave.Controlled=function(a,b){void 0!==a&&(window.pbehave.PBehave.call(this,a,b),this._jumps=0,this._markAt="")};window.pbehave.Controlled.prototype=new window.pbehave.PBehave;window.pbehave.Controlled.constructor=window.pbehave.Controlled;
window.pbehave.Controlled.prototype.everyFrame=function(){if(!window.events.getVar("plat.edit")){dusk.mods.keyboard.isKeyPressed(37)&&this._entity.dx>-this._entity.eProp("hspeed")?this._entity.dx-=this._entity.eProp("haccel"):dusk.mods.keyboard.isKeyPressed(39)&&this._entity.dx<this._entity.eProp("hspeed")&&(this._entity.dx+=this._entity.eProp("haccel"));if(dusk.mods.keyboard.isKeyPressed(38)&&-4<this._entity.dy&&(0==this._jumps&&this._events.getVar("plat.skill.jump")||1==this._jumps&&this._events.getVar("plat.skill.dubjump")||
this._events.getVar("plat.skill.infinijump")))this._entity.dy=-this._entity.eProp("jump"),this._jumps++;1==this._entity.path("../../scheme").tilePointIn(this._entity.x+this._entity.prop("width")/2,this._entity.y+this._entity.prop("height")/2)[1]&&this._entity.path("../../scheme").tilePointIn(this._entity.x+this._entity.prop("width")/2,this._entity.y+this._entity.prop("height")/2)[0]!=this._markAt&&(this._markAt=this._entity.path("../../scheme").tilePointIn(this._entity.x+this._entity.prop("width")/
2,this._entity.y+this._entity.prop("height")/2)[0],this._events.run([{a:"fire",up:!1,mark:this._markAt,activator:this._entity.comName,room:this._entity.path("../..").prop("room"),event:"plat-mark"}],this._events.thread))}};window.pbehave.Controlled.prototype.onLand=function(){this._jumps=0};window.pbehave.Controlled.prototype.onCollideTop=function(){this._jumps=0};dusk.pbehave.Fall={};window.pbehave.Fall=function(a,b){void 0!==a&&(window.pbehave.PBehave.call(this,a,b),!this._entity.eProp("speed")&&0!==this._entity.eProp("speed")&&this._entity.eProp("speed",2))};window.pbehave.Fall.prototype=new window.pbehave.PBehave;window.pbehave.Fall.constructor=window.pbehave.Fall;
window.pbehave.Fall.prototype.everyFrame=function(){for(var a=this._entity.teatherClients().length-1;0<=a;a--)0>this._entity.teatherClients()[a][0].dy&&this._entity.unteather(this._entity.teatherClients()[a][0]);this._entity.teatherClients().length||(this._entity.dy=0)};window.pbehave.Fall.prototype.onCollideBottom=function(a){this._entity.teather(a,"uX");this._entity.dy=this._entity.eProp("speed")};window.sgui={};dusk.sgui={};dusk.sgui.Component={};dusk.sgui.NullCom={};
sgui.Component=function(a,b,c){void 0!==a&&(this._container=a,this._events=b,this.comName=c,this.y=this.x=0,this.visible=!0,this.alpha=1,this._width=this._height=0,this._mark=null,this.cache=this._redrawBooked=!1,this._cacheCanvas=null,this.downFlow=this.upFlow=this.rightFlow=this.leftFlow="",this._stuffActions=[],this._keyHandlers=[],this._frameHandlers=[],this._actionHandlers=[],this._drawHandlers=[],this._propHandlers={},this._propMasks={},this._action=[],this.enabled=!0,this._active=this._focused=
this.locked=!1,this._thread="",this._floatTime=this._floatSpeed=this.open=0,this._floatDir="u",this._fadeEnd=this._fade=0,this._registerPropMask("x","x",!0),this._registerPropMask("y","y",!0),this._registerPropMask("width","_width",!0),this._registerPropMask("height","_height",!0),this._registerPropMask("alpha","alpha",!0),this._registerPropMask("visible","visible",!0),this._registerPropMask("mark","_mark",!0),this._registerPropMask("flow-up","_upFlow",!0),this._registerPropMask("flow-down","_downFlow",
!0),this._registerPropMask("flow-left","_leftFlow",!0),this._registerPropMask("flow-right","_rightFlow",!0),this._registerPropMask("enabled","enabled",!0),this._registerPropMask("action","_action",!0),this._registerProp("delete",function(a,b){b&&this._container.deleteComponent(this.comName)},null),this._registerProp("float",this._setFloat,null),this._registerProp("fade",this._setFade,null),this._registerActionHandler("actionProp",this._actionProp,this))};sgui.Component.prototype.className="Component";
sgui.Component.prototype.isAContainer=!1;sgui.Component.prototype.frame=function(a){for(var b=this._frameHandlers.length-1;0<=b;b--)this._frameHandlers[b]&&this._frameHandlers[b].call(this,a)};sgui.Component.prototype._registerKeyHandler=function(a,b,c,d,e){for(var f=this._keyHandlers.length-1;0<=f;f--)if(this._keyHandlers[f][0]==a&&this._keyHandlers[f][1]==b&&this._keyHandlers[f][2]==c){console.warn(a+" on "+this.comName+" is already registered.");return}this._keyHandlers.push([a,b,c,d,e])};
sgui.Component.prototype._registerFrameHandler=function(a){this._frameHandlers.push(a)};sgui.Component.prototype._clearFrameHandler=function(a){for(var b in this._frameHandlers)this._frameHandlers[b]==a&&delete this._frameHandlers[b]};sgui.Component.prototype._registerActionHandler=function(a,b){this._actionHandlers[a]=b};sgui.Component.prototype._registerProp=function(a,b,c,d){void 0!==this._propMasks[a]&&delete this._propMasks[a];this._propHandlers[a]=[b,c,d]};
sgui.Component.prototype._registerPropMask=function(a,b,c){this._propMasks[a]=[b,c]};sgui.Component.prototype._actionProp=function(){if(this._action.length)return this._events.run(this._action,"_"+this.comName),!0};sgui.Component.prototype._doAction=function(a){var b=!1,c;for(c in this._actionHandlers)b=this._actionHandlers[c].call(this,a)?!0:b;if(b)return!0};
sgui.Component.prototype.keypress=function(a){if(this.isAContainer&&this.containerKeypress(a))return!0;for(var b=this._keyHandlers.length-1;0<=b;b--)if(0>this._keyHandlers[b][0]&&(this._keyHandlers[b][1]==a.shiftKey&&this._keyHandlers[b][2]==a.ctrlKey)&&this._keyHandlers[b][3].call(this,a))return!0;if(a.shiftKey)for(b=this._keyHandlers.length-1;0<=b;b--)if(0>this._keyHandlers[b][0]&&(!1==this._keyHandlers[b][1]&&this._keyHandlers[b][2]==a.ctrlKey)&&this._keyHandlers[b][3].call(this,a))return!0;switch(a.which){case 37:if(this._leftAction(a)&&
this._leftFlow&&this._container.flow(this._leftFlow))return!0;break;case 38:if(this._upAction(a)&&this._upFlow&&this._container.flow(this._upFlow))return!0;break;case 39:if(this._rightAction(a)&&this._rightFlow&&this._container.flow(this._rightFlow))return!0;break;case 40:if(this._downAction(a)&&this._downFlow&&this._container.flow(this._downFlow))return!0;break;case 32:if(this._doAction(a))return!0;default:for(b=this._keyHandlers.length-1;0<=b;b--)if(this._keyHandlers[b][0]==a.which&&this._keyHandlers[b][1]==
a.shiftKey&&this._keyHandlers[b][2]==a.ctrlKey)return this._keyHandlers[b][3].call(this,a);for(b=this._keyHandlers.length-1;0<=b;b--)if(this._keyHandlers[b][0]==a.which&&!1==this._keyHandlers[b][1]&&this._keyHandlers[b][2]==a.ctrlKey)return this._keyHandlers[b][3].call(this,a)}return!1};sgui.Component.prototype._leftAction=function(){return!0};sgui.Component.prototype._rightAction=function(){return!0};sgui.Component.prototype._upAction=function(){return!0};sgui.Component.prototype._downAction=function(){return!0};
sgui.Component.prototype.parseProps=function(a,b){b&&(this._thread=b);var c=[],d;for(d in a)c[c.length]=d;for(;c.length;)for(d=c.length-1;0<=d;d--){if(this._propHandlers[c[d]]&&this._propHandlers[c[d]][2]){for(var e=this._propHandlers[c[d]][2].length-1;0<=e;e--)-1!==c.indexOf(this._propHandlers[c[d]][2][e])&&(e=-2);if(-1>e)continue}a[c[d]]&&void 0!==a[c[d]].to?(this._events.setVar(a[c[d]].to,this.prop[c[d]]),void 0!==a[c[d]].value&&this.prop(c[d],a[c[d]].value)):this.prop(c[d],a[c[d]]);c.splice(d,
1)}};sgui.Component.prototype.prop=function(a,b){if(void 0!==this._propMasks[a]){if(void 0===b)return this[this._propMasks[a][0]];this[this._propMasks[a][0]]=b;this._propMasks[a][1]&&this.bookRedraw();return b}return void 0!==this._propHandlers[a]?void 0!==b?this._propHandlers[a][0].call(this,a,b):this._propHandlers[a][1].call(this,a):null};
sgui.Component.prototype._theme=function(a,b){void 0===this._events.getVar("theme."+this._events.getVar("theme.current")+"."+a)&&void 0!==b&&this._events.setVar("theme."+this._events.getVar("theme.current")+"."+a,b);return this._events.getVar("theme."+this._events.getVar("theme.current")+"."+a)};
sgui.Component.prototype._setFade=function(a,b){this._awaitNext();"from"in b?this.prop("alpha",b.from):this.prop("alpha",0);this._fade="speed"in b?Number(b.speed):Number(0.05);this._fadeEnd="end"in b?b.to:1;this._registerFrameHandler(this._fadeEffect)};sgui.Component.prototype._setFloat=function(a,b){this._awaitNext();this._floatTime="for"in b?b["for"]:10;this._floatSpeed="speed"in b?b.speed:5;this._floatDir="dir"in b?b.dir:"u";this._registerFrameHandler(this._floatEffect)};
sgui.Component.prototype._fadeEffect=function(){this.alpha<this._fadeEnd&&0<this._fade||this.alpha>this._fadeEnd&&0>this._fade?(this.alpha+=this._fade,this.bookRedraw()):(this.alpha=this._fadeEnd,this.bookRedraw(),this._fade=0,this._clearFrameHandler(this._fadeEffect),this._next())};
sgui.Component.prototype._floatEffect=function(){this._floatTime--;switch(this._floatDir){case "d":this.y+=this._floatSpeed;break;case "l":this.x-=this._floatSpeed;break;case "r":this.x+=this._floatSpeed;break;default:case "u":this.y-=this._floatSpeed}this.bookRedraw();0==this._floatTime&&(this._clearFrameHandler(this._floatEffect),this._next())};sgui.Component.prototype._awaitNext=function(a){void 0===a&&(a=1);this.open+=a;this._events.awaitNext(this._thread,a)};
sgui.Component.prototype._next=function(a){void 0===a&&(a=1);this.open-=a;this._events.next(this._thread)};sgui.Component.prototype._registerDrawHandler=function(a){this._drawHandlers.push(a)};
sgui.Component.prototype.draw=function(a){if(this.visible){var b=a.save();(this.x||this.y)&&a.translate(~~this.x,~~this.y);1!=this.alpha&&(a.globalAlpha=this.alpha);for(var c=0;c<this._drawHandlers.length;c++)this._drawHandlers[c].call(this,a);null!==this._mark&&(a.strokeStyle=this._mark,a.strokeRect(0,0,this.prop("width"),this.prop("height")));a.restore(b);this._redrawBooked=!1}};sgui.Component.prototype.bookRedraw=function(){!this._redrawBooked&&this._container&&(this._redrawBooked=!0,this._container.bookRedraw())};
sgui.Component.prototype.path=function(a){if(!a)return duskWolf.error("path is undefined."),null;if(-1!==a.indexOf("/"))var b=a.split("/",1)[0],c=a.substr(b.length+1);else b=a,c="";switch(b){case "..":return c?this._container.path(c):this._container;case "":return"Pane"==this.className?this.path(c):this._container.path(c);default:if(this.isAContainer)return c?this.getComponent(b).path(c):this.getComponent(b);duskWolf.warn(a+" from "+this.comName+" was not found.")}return null};
sgui.Component.prototype.onLooseFocus=function(){this._focused=!1;this.bookRedraw()};sgui.Component.prototype.onGetFocus=function(){this._focused=!0;this.bookRedraw()};sgui.Component.prototype.onDeactive=function(){this._active=!1;this.bookRedraw()};sgui.Component.prototype.onActive=function(){this._active=!0;this.bookRedraw()};sgui.Component.prototype.toString=function(){return"[sgui "+this.className+" "+this.comName+"]"};
sgui.NullCom=function(a,b,c){sgui.Component.call(this,a,b,c);this.prop("visible",!1)};sgui.NullCom.prototype=new sgui.Component;sgui.NullCom.constructor=sgui.NullCom;sgui.NullCom.prototype.className="NullCom";dusk.sgui.DecimalTile={};
sgui.DecimalTile=function(a,b,c){void 0!==a&&(sgui.Component.call(this,a,b,c),this._img=null,this._sheight=this._theme("dtile.sheight",24),this._swidth=this._theme("dtile.swidth",24),this._ty=this._tx=0,this._registerProp("src",this._setImage,function(){return this._img}),this._registerPropMask("sprite-height","_swidth",!0),this._registerPropMask("sprite-width","_sheight",!0),this._registerProp("tile",function(a,b){this._setTile(b.split(",")[0],b.split(",")[1])},function(){this._getTile()}),this._registerDrawHandler(this._tileDraw))};
sgui.DecimalTile.prototype=new sgui.Component;sgui.DecimalTile.constructor=sgui.DecimalTile;sgui.DecimalTile.prototype.className="DecimalTile";sgui.DecimalTile.prototype._tileDraw=function(a){this._img&&a.drawImage(this._img,this._swidth*this._tx,this._sheight*this._ty,this._swidth,this._sheight,0,0,this.prop("width"),this.prop("height"))};sgui.DecimalTile.prototype._setImage=function(a,b){b?(this._img=dusk.data.grabImage(b),this.bookRedraw()):console.warn(this.comName+" tried to set image to nothing.")};
sgui.DecimalTile.prototype._getTile=function(){return this._tx+","+this._ty};sgui.DecimalTile.prototype._setTile=function(a,b){null===b&&(a=a.split(",")[0],b=a.split(",")[1]);this._tx=a;this._ty=b};sgui.DecimalTile.prototype.snapX=function(a){this.x=a?Math.ceil(this.x/this.prop("width"))*this.prop("width"):Math.floor(this.x/this.prop("width"))*this.prop("width")};
sgui.DecimalTile.prototype.snapY=function(a){this.y=a?Math.ceil(this.y/this.prop("height"))*this.prop("height"):Math.floor(this.y/this.prop("height"))*this.prop("height")};sgui.DecimalTile.prototype.gridGo=function(a,b){this.x=a*this.prop("width");this.y=b*this.prop("height")};dusk.sgui.IContainer={};sgui.IContainer=function(a,b,c){void 0!==a&&sgui.Component.call(this,a,b,c)};sgui.IContainer.prototype=new sgui.Component;sgui.IContainer.constructor=sgui.IContainer;sgui.IContainer.prototype.containerKeypress=function(){console.warn('Container has not implemented "containerKeypress".')};sgui.IContainer.prototype.deleteComponent=function(){console.warn('Container has not implemented "deleteComponent".')};sgui.IContainer.prototype.getComponent=function(){console.warn('Container has not implemented "getComponent".')};
sgui.IContainer.prototype.flow=function(){console.warn('Container has not implemented "flow".')};sgui.IContainer.prototype.isAContainer=!0;dusk.sgui.Group={};
sgui.Group=function(a,b,c){void 0!==a&&(sgui.Component.call(this,a,b,c),this._components={},this._drawOrder=[],this._focusedCom="",this._focused=this._active=!1,this._registerProp("focus",function(a,b){if(this._focusedCom!=b)return this.focus(b)},function(){return this._focusedCom}),this._registerProp("children",this._children,function(){return this._components}),this._registerProp("allChildren",this._allChildren,function(){return this._components}),this._registerDrawHandler(this._groupDraw),this._registerFrameHandler(this._groupFrame),
this._newComponent("blank","NullCom"),this.prop("focus","blank"))};sgui.Group.prototype=new sgui.IContainer;sgui.Group.constructor=sgui.Group;sgui.Group.prototype.className="Group";sgui.Group.prototype.containerKeypress=function(a){return this.getFocus().keypress(a)};
sgui.Group.prototype._newComponent=function(a,b){if(b)return b in sgui||(duskWolf.error(b+" is not a valid component type."),b="NullCom"),this._components[a]=new sgui[b](this,this._events,a.toLowerCase()),this._drawOrder[this._drawOrder.length]=a,this.bookRedraw(),this._components[a];duskWolf.error("Cannot create a new component of type null!")};
sgui.Group.prototype._children=function(a,b){if("length"in b)for(var c=0;c<b.length;c++)b[c].name&&this.getComponent(b[c].name.toLowerCase(),b[c].type)?this.getComponent(b[c].name.toLowerCase()).parseProps(b[c],this._thread):b[c].name?duskWolf.warn(b.name+" has not been given a type and does not exist, ignoring."):duskWolf.warn("A component has no name in "+this.comName+".");else{if(b.name&&this._getComponent(b.name.toLowerCase(),b.type))return this._getComponent(b.name.toLowerCase()).parseProps(b,
this._thread);b.name?duskWolf.warn(b.name+" has not been given a type and does not exist, ignoring."):duskWolf.warn("A component has no name in "+this.comName+".")}};sgui.Group.prototype._allChildren=function(a,b){for(var c in this._components)this._components[c].parseProps(b,this._thread)};sgui.Group.prototype._groupDraw=function(a){for(var b=0;b<this._drawOrder.length;b++)this._drawOrder[b]in this._components&&this._components[this._drawOrder[b]].draw(a)};sgui.Group.prototype._groupFrame=function(a){for(var b in this._components)this._components[b].frame(a)};
sgui.Group.prototype.getComponent=function(a,b){return this._components[a.toLowerCase()]?this._components[a.toLowerCase()]:b?this._newComponent(a,b):null};sgui.Group.prototype.deleteComponent=function(a){if(this._components[a.toLowerCase()])return this._getFocusName()==a.toLowerCase()&&this.focus("blank"),delete this._components[a.toLowerCase()],delete this._drawOrder[this._drawOrder.indexOf(a.toLowerCase())],this.bookRedraw(),!0};
sgui.Group.prototype.focus=function(a){if(this._components[this._focusedCom]){if(this._components[this._focusedCom].locked)return!1;if(this._active)this._components[this._focusedCom].onDeactive();this._components[this._focusedCom].onLooseFocus()}if(this._components[a.toLowerCase()]){this._focusedCom=a.toLowerCase();this._components[this._focusedCom].onGetFocus();if(this._active)this._components[this._focusedCom].onActive();return!0}console.warn(a+" was not found, couldn't set focus.");this._focusedCom=
"blank";return!1};sgui.Group.prototype.getFocus=function(){return this._components[this._focusedCom]};sgui.Group.prototype.flow=function(a){return this.getComponent(a)&&this.getComponent(a).enabled&&this.focus(a)};sgui.Group.prototype.onDeactive=function(){this._active=!1;this.getFocus().onDeactive()};sgui.Group.prototype.onActive=function(){this._active=!0;this.getFocus().onActive()};dusk.sgui.Grid={};sgui.Grid=function(a,b,c){void 0!==a&&(sgui.Group.call(this,a,b,c),this._rows=this._theme("grid.rows",5),this._cols=this._theme("grid.cols",5),this._hspacing=this._theme("grid.spacing.h",0),this._vspacing=this._theme("grid.spacing.v",0),this._registerPropMask("spacing-v","_vspacing",!1),this._registerPropMask("spacing-h","_hspacing",!1),this._registerPropMask("rows","_rows",!1),this._registerPropMask("cols","_cols",!1),this._registerProp("populate",this._populate,null,["rows","cols"]))};
sgui.Grid.prototype=new sgui.Group;sgui.Grid.constructor=sgui.Grid;sgui.Grid.prototype.className="Grid";sgui.Grid.prototype._populate=function(a,b){for(var c in this._components)"blank"!=c&&this.deleteComponent(c);for(c=0;c<this.prop("rows");c++)for(var d=0;d<this.prop("cols");d++){var e=this.getComponent(d+","+c,b.type);e.parseProps(b,this._thread);e.parseProps({y:c*e.prop("height")+c*this._vspacing,x:d*e.prop("width")+d*this._vspacing},this._thread)}this.prop("focus","0,0")};
sgui.Grid.prototype.ajust=function(){for(var a=0;a<this.rows;a++)for(var b=0;b<this.cols;b++){var c=this.getComponent(b+","+a);c.doStuff({y:a*c.prop("height")+a*this._vspacing,x:b*c.prop("width")+b*this._hspacing},this._thread)}};sgui.Grid.prototype._leftAction=function(){var a=this.prop("focus").split(",")[0],b=this.prop("focus").split(",")[1];return this.getComponent(a-1+","+b)?(this.focus(a-1+","+b),!1):!0};
sgui.Grid.prototype._rightAction=function(){var a=this.prop("focus").split(",")[0],b=this.prop("focus").split(",")[1];return this.getComponent(Number(a)+1+","+b)?(this.focus(Number(a)+1+","+b),!1):!0};sgui.Grid.prototype._upAction=function(){var a=this.prop("focus").split(",")[0],b=this.prop("focus").split(",")[1];return this.getComponent(a+","+(b-1))?(this.focus(a+","+(b-1)),!1):!0};
sgui.Grid.prototype._downAction=function(){var a=this.prop("focus").split(",")[0],b=this.prop("focus").split(",")[1];return this.getComponent(a+","+(Number(b)+1))?(this.focus(a+","+(Number(b)+1)),!1):!0};dusk.sgui.Image={};sgui.Image=function(a,b,c){void 0!==a&&(sgui.Component.call(this,a,b,c),this._img=null,this._registerProp("src",this._setImage,function(){return this._img}),this._registerDrawHandler(this._imageDraw))};sgui.Image.prototype=new sgui.Component;sgui.Image.constructor=sgui.Image;sgui.Image.prototype.className="Image";sgui.Image.prototype._imageDraw=function(a){this._img&&a.drawImage(this._img,0,0,this.prop("width"),this.prop("height"))};
sgui.Image.prototype._setImage=function(a,b){b?(this._img=dusk.data.grabImage(b),this.bookRedraw()):duskWolf.warn(this.comName+" tried to set image to nothing.")};dusk.sgui.FocusChecker={};
sgui.FocusChecker=function(a,b,c){void 0!==a&&(sgui.Image.call(this,a,b,c),this._inactiveImg=this._theme("fc.inactive","Examples/inactive.png"),this._focusedImg=this._theme("fc.focused","Examples/focused.png"),this._activeImg=this._theme("fc.active","Examples/active.png"),this._registerStuff(this._focusStuff),this._registerPropMask("image-inactive","_inactiveImg",!0),this._registerPropMask("image-focused","_focusedImg",!0),this._registerPropMask("image-active","_activeImg",!0),this.prop("src",this._inactiveImg))};
sgui.FocusChecker.prototype=new sgui.Image;sgui.FocusChecker.constructor=sgui.FocusChecker;sgui.FocusChecker.prototype.className="FocusChecker";sgui.FocusChecker.prototype.onLooseFocus=function(){this._inactiveImg&&this.prop("src",this._inactiveImg)};sgui.FocusChecker.prototype.onGetFocus=function(){this._focusedImg&&this.prop("src",this._focusedImg)};sgui.FocusChecker.prototype.onDeactive=function(){this._focusedImg&&this.prop("src",this._focusedImg)};
sgui.FocusChecker.prototype.onActive=function(){this._activeImg&&this.prop("src",this._activeImg)};dusk.sgui.Pane={};sgui.Pane=function(a,b,c){this._sgui=a;sgui.Group.call(this,null,b,c);this._registerProp("active",function(a,b){b&&this._sgui.setActivePane(this.comName)},function(){return this.active})};sgui.Pane.prototype=new sgui.Group;sgui.Pane.constructor=sgui.Pane;sgui.Pane.prototype.className="Pane";sgui.Pane.prototype.bookRedraw=function(){this._redrawBooked||(this._sgui.bookRedraw(),this._redrawBooked=!0)};dusk.mods.simpleGui={};
dusk.mods.simpleGui.init=function(){dusk.events.registerKeyHandler("SGuiKey",function(a){this.getActivePane().keypress(a)},this);dusk.events.registerFrameHandler("SGuiFrame",function(a){for(var b in this._panes)this._panes[b].frame(a)},this);this._panes={};this._activePane="";this._redrawBooked=!1;this.setActivePane("blank");dusk.events.setVar("sys.sg.width",0);dusk.events.setVar("sys.sg.height",0);this._cacheCanvas=document.createElement("canvas");dusk.events.setVar("theme.default.box","#eeeeee");
dusk.events.setVar("theme.default.border","#cccccc");dusk.events.setVar("theme.default.borderActive","#ff5555");dusk.events.setVar("theme.current","default");dusk.events.registerStartHandler(this._onStart,this);dusk.events.registerAction("sg-path",this._doPath,this,[["pane",!0,"STR"],["path",!0,"STR"]]);dusk.events.registerAction("pane",this._doComponent,this,[["name",!0,"STR"]]);dusk.events.registerAction("draw",function(){this.draw()},this,[])};
dusk.mods.simpleGui._onStart=function(){dusk.events.setVar("sys.sg.width",$("#"+dusk.canvas)[0].width);dusk.events.setVar("sys.sg.height",$("#"+dusk.canvas)[0].height);dusk.events.setVar("sys.sg.drawable",!0);this._cacheCanvas.height=dusk.events.getVar("sys.sg.height");this._cacheCanvas.width=dusk.events.getVar("sys.sg.width");this._cacheCanvas.style.imageRendering="-webkit-optimize-contrast";this._cacheCanvas.getContext("2d").mozImageSmoothingEnabled=!1;this._cacheCanvas.getContext("2d").textBaseline=
"middle"};dusk.mods.simpleGui.newPane=function(a){if(this.getPane(a,!0))return duskWolf.error("Pane "+a+" already exists!"),null;this._panes[a.toLowerCase()]=new sgui.Pane(this,dusk.events,a);return this._panes[a.toLowerCase()]};dusk.mods.simpleGui.getPane=function(a,b){return this._panes[a.toLowerCase()]?this._panes[a.toLowerCase()]:b?null:this.newPane(a)};
dusk.mods.simpleGui._doComponent=function(a){if(void 0===a.name)throw new dusk.errors.PropertyMissing(a.a,"vars");this.getPane(a.name).parseProps(dusk.events.replaceVar(a,!0),dusk.events.thread)};dusk.mods.simpleGui.setActivePane=function(a){if(this.getActivePane())this.getActivePane().onDeactive();this.getPane(a);this._activePane=a.toLowerCase();this.getActivePane().onActive()};dusk.mods.simpleGui.getActivePane=function(){return this._panes[this._activePane]};
dusk.mods.simpleGui.draw=function(){if(!this._redrawBooked||!dusk.events.getVar("sys.sg.drawable"))return!1;$("#"+dusk.canvas)[0].getContext("2d").clearRect(0,0,dusk.events.getVar("sys.sg.width"),dusk.events.getVar("sys.sg.height"));this._cacheCanvas.getContext("2d").clearRect(0,0,dusk.events.getVar("sys.sg.width"),dusk.events.getVar("sys.sg.height"));for(var a in this._panes)this._panes[a].draw(this._cacheCanvas.getContext("2d"));$("#"+dusk.canvas)[0].getContext("2d").drawImage(this._cacheCanvas,
0,0,dusk.events.getVar("sys.sg.width"),dusk.events.getVar("sys.sg.height"));this._redrawBooked=!1;return!0};dusk.mods.simpleGui._doPath=function(a){if(!a.path)throw new dusk.errors.PropertyMissing(a.a,"path");if(!a.pane)throw new dusk.errors.PropertyMissing(a.a,"pane");this.path(a.pane,a.path).parseProps(a,dusk.events.thread)};dusk.mods.simpleGui.path=function(a,b){return this.getPane(a).path(b)};dusk.mods.simpleGui.bookRedraw=function(){this._redrawBooked=!0};dusk.mods.simpleGui.init();dusk.sgui.Rect={};sgui.Rect=function(a,b,c){void 0!==a&&(sgui.Component.call(this,a,b,c),this._colour=this._theme("box"),this._bColour=this._theme("border"),this._bWidth=1,this._registerPropMask("colour","_colour",!0),this._registerPropMask("color","_colour",!0),this._registerPropMask("border-colour","_bColour",!0),this._registerPropMask("border-color","_bColour",!0),this._registerPropMask("border-width","_bWidth",!0),this._registerDrawHandler(this._rectDraw))};sgui.Rect.prototype=new sgui.Component;
sgui.Rect.constructor=sgui.Rect;sgui.Rect.prototype.className="Rect";sgui.Rect.prototype._rectDraw=function(a){a.fillStyle=this._colour;a.strokeStyle=this._bColour;a.lineWidth=this._bWidth;a.fillRect(0,0,this.prop("width"),this.prop("height"));this._bWidth&&a.strokeRect(0,0,this.prop("width"),this.prop("height"))};dusk.sgui.Single={};sgui.Single=function(a,b,c){void 0!==a&&(sgui.Component.call(this,a,b,c),this._component=null,this.newComponent("blank","NullCom"),this._registerProp("child",this._singleChild,function(){return this._component}),this._registerDrawHandler(this._singleDraw),this._registerFrameHandler(this._singleFrame))};sgui.Single.prototype=new sgui.IContainer;sgui.Single.constructor=sgui.Group;sgui.Single.prototype.className="Single";sgui.Single.prototype.containerKeypress=function(a){return this._component.keypress(a)};
sgui.Single.prototype.newComponent=function(a,b){if(b)return this._component=new sgui[b](this,this._events,a.toLowerCase());duskWolf.error("Cannot create a new component of type null!")};sgui.Single.prototype._singleChild=function(a,b){b.name&&this.getComponent(b.name.toLowerCase(),b.type)?this.getComponent(b.name.toLowerCase()).parseProps(this._events.replaceVar(b),this._thread):console.warn(b.name+" has not been given a type and does not exist, ignoring.")};sgui.Single.prototype._singleDraw=function(a){this._component.draw(a)};
sgui.Single.prototype.getComponent=function(a,b){return this._component.comName==a.toLowerCase()||"*"==a||""===a?this._component:b?this.newComponent(a,b):null};sgui.Single.prototype.deleteComponent=function(a){if(this._component.comName==a.toLowerCase()||"*"==a||!a)return this.newComponent("blank","NullCom"),!0};sgui.Single.prototype._singleFrame=function(){this.getComponent("").frame()};sgui.Single.prototype.flow=function(a){return this._container.flow(a)};sgui.Single.prototype.onDeactive=function(){this._component.onDeactive()};
sgui.Single.prototype.onActive=function(){this._component.onActive()};dusk.sgui.CentreScroller={};sgui.CentreScroller=function(a,b,c){void 0!==a&&(sgui.Single.call(this,a,b,c),this._registerProp("seek",this._updateSeek,null))};sgui.CentreScroller.prototype=new sgui.Single;sgui.CentreScroller.constructor=sgui.CentreScroller;sgui.CentreScroller.prototype.className="CentreScroller";sgui.CentreScroller.prototype._updateSeek=function(a,b){this.x=-b[0]+this.prop("width")/2;this.y=-b[1]+this.prop("height")/2};dusk.sgui.DirListener={};sgui.DirListener=function(a,b,c){void 0!==a&&(sgui.Single.call(this,a,b,c),this._up=[],this._down=[],this._left=[],this._right=[],this._registerPropMask("action-up","_up",!1),this._registerPropMask("action-down","_down",!1),this._registerPropMask("action-left","_left",!1),this._registerPropMask("action-right","_right",!1))};sgui.DirListener.prototype=new sgui.Single;sgui.DirListener.constructor=sgui.DirListener;sgui.DirListener.prototype.className="DirListener";
sgui.DirListener.prototype._upAction=function(){return this._up?(this._events.run(this._up,"_"+this.comName),!1):!0};sgui.DirListener.prototype._downAction=function(){return this._down?(this._events.run(this._down,"_"+this.comName),!1):!0};sgui.DirListener.prototype._leftAction=function(){return this._left?(this._events.run(this._left,"_"+this.comName),!1):!0};sgui.DirListener.prototype._rightAction=function(){return this._right?(this._events.run(this._right,"_"+this.comName),!1):!0};dusk.sgui.Label={};dusk.sgui.Text={};dusk.sgui.TextBox={};
sgui.Label=function(a,b,c){void 0!==a&&(sgui.Component.call(this,a,b,c),this._registerPropMask("text","_text",!0),this._registerPropMask("font","_font",!0),this._registerPropMask("colour","_colour",!0),this._registerPropMask("color","_colour",!0),this._registerPropMask("padding","_padding",!0),this._registerPropMask("size","_size",!0),this._registerProp("width",this._setWidth,this._getWidth,["font","text"]),this._registerProp("height",this._setHeight,this._getHeight,["font","text"]),this._text="",
this._width=-1,this._size=this._theme("label.size",14),this._font=this._theme("label.font","sans"),this._colour=this._theme("label.colour","#000000"),this._padding=this._theme("label.padding",5),this._registerDrawHandler(this._labelDraw))};sgui.Label.prototype=new sgui.Component;sgui.Label.constructor=sgui.Label;sgui.Label.prototype.className="Label";
sgui.Label.prototype._labelDraw=function(a){this._text&&(a.fillStyle=this.prop("colour"),a.font=this.prop("size")+"px "+this.prop("font"),0<this.prop("width")?a.fillText(this._text,this.prop("padding"),(this.prop("height")>>1)+(this.prop("padding")>>1),~~this.prop("width")-(this._padding<<1)):a.fillText(this._text,this.prop("padding"),(this.prop("height")>>1)+(this.prop("padding")>>1)))};sgui.Label.prototype._getWidth=function(){return this.measure(this.prop("text"))+(this._padding<<1)};
sgui.Label.prototype._setWidth=function(a,b){this._width=b-(this._padding<<1);return b};sgui.Label.prototype._getHeight=function(){return this.prop("size")+(this._padding<<1)};sgui.Label.prototype._setHeight=function(a,b){this.prop("size",b-(this._padding<<1));return this.prop("size")+(this._padding<<1)};
sgui.Label.prototype.measure=function(a){if(-1!=this._width)return this._width;var b=$("#"+dusk.canvas)[0].getContext("2d"),c=b.save();b.font=this.prop("size")+"px "+this.prop("font");a=b.measureText(a).width;b.restore(c);return a};sgui.Text=function(a,b,c){void 0!==a&&(sgui.Label.call(this,a,b,c),this._watch="",this._registerPropMask("watch","_watch",!0),this._registerFrameHandler(this._checkUpdate))};sgui.Text.prototype=new sgui.Label;sgui.Text.constructor=sgui.Text;
sgui.Text.prototype.className="Text";sgui.Text.prototype._checkUpdate=function(){this.prop("watch")&&(void 0!==this._events.getVar(this.prop("watch"))&&this._events.getVar(this.prop("watch"))!=this.prop("text"))&&this.prop("text",this._events.getVar(this.prop("watch")))};
sgui.TextBox=function(a,b,c){void 0!==a&&(sgui.Text.call(this,a,b,c),this._registerPropMask("border","_border",!0),this._registerPropMask("border-active","_borderActive",!0),this._border=this._theme("border"),this._borderActive=this._theme("borderActive"),this._registerDrawHandler(this._boxDraw),this._registerKeyHandler(-1,!1,!1,this._boxKey,this))};sgui.TextBox.prototype=new sgui.Text;sgui.TextBox.constructor=sgui.TextBox;sgui.TextBox.prototype.className="TextBox";
sgui.TextBox.prototype._boxDraw=function(a){a.strokeStyle=this._active?this.prop("border-active"):this.prop("border");a.strokeRect(0,0,this.prop("width"),this.prop("height"))};
sgui.TextBox.prototype._boxKey=function(a){var b=this._events.getMod("Keyboard").lookupCode(a.keyCode);void 0===this._events.getVar(this.prop("watch"))&&this._events.setVar(this.prop("watch"),"");return b[1]?(this._events.setVar(this.prop("watch"),this._events.getVar(this.prop("watch"))+(a.shiftKey?b[0].toUpperCase():b[0])),!0):"BACKSPACE"==b[0]?(this._events.setVar(this.prop("watch"),this._events.getVar(this.prop("watch")).substr(0,this._events.getVar(this.prop("watch")).length-1)),!0):"ENTER"==
b[0]?(this._doAction(a),!0):!1};dusk.sgui.Tile={};sgui.Tile=function(a,b,c){void 0!==a&&(sgui.Component.call(this,a,b,c),this._img=null,this._ssize=this._theme("tile.ssize",4),this._width=1<<this._ssize,this._height=1<<this._ssize,this._ty=this._tx=0,this._registerProp("src",this._setImage,function(){return this._img}),this._registerProp("tile",function(a,b){this._setTile(b.split(",")[0],b.split(",")[1])},function(){this._getTile()}),this._registerPropMask("sprite-size","_ssize",!0),this._registerDrawHandler(this._tileDraw))};
sgui.Tile.prototype=new sgui.Component;sgui.Tile.constructor=sgui.Tile;sgui.Tile.prototype.className="Tile";sgui.Tile.prototype._tileDraw=function(a){this._img&&a.drawImage(this._img,this._tx<<this._ssize,this._ty<<this._ssize,1<<this._ssize,1<<this._ssize,0,0,this.prop("width"),this.prop("height"))};sgui.Tile.prototype._setImage=function(a,b){this._img=dusk.data.grabImage(b)};sgui.Tile.prototype._getTile=function(){return this._tx+","+this._ty};
sgui.Tile.prototype._setTile=function(a,b){void 0===b&&(a=a.split(",")[0],b=a.split(",")[1]);this._tx=a;this._ty=b};sgui.Tile.prototype.snapX=function(a){this.x=a?Math.ceil(this.x/this.prop("width"))*this.prop("width"):Math.floor(this.x/this.prop("width"))*this.prop("width")};sgui.Tile.prototype.snapY=function(a){this.y=a?Math.ceil(this.y/this.prop("height"))*this.prop("height"):Math.floor(this.y/this.prop("height"))*this.prop("height")};
sgui.Tile.prototype.gridGo=function(a,b){this.x=a*this.prop("width");this.y=b*this.prop("height")};dusk.sgui.PlatEntity={};sgui.PlatEntity=function(a,b,c){void 0!==a&&(sgui.Tile.call(this,a,b,c),this.dx=this.dy=0,this._behave=null,this._eProps={},this.typeChange("default"),this._touchers={l:[],r:[],u:[],d:[]},this._teatherClients=[],this._teatherHost=null,this._ssize=this._events.getVar("plat.ssize"),this.prop("width",1<<this._events.getVar("plat.tsize")),this.prop("height",1<<this._events.getVar("plat.tsize")))};sgui.PlatEntity.prototype=new sgui.Tile;sgui.PlatEntity.constructor=sgui.PlatEntity;
sgui.PlatEntity.prototype.className="PlatEntity";
sgui.PlatEntity.prototype.moveAndCollide=function(){if(!this._teatherHost||-1!==this._teatherHost[1].indexOf("l")||-1!==this._teatherHost[1].indexOf("r"))this.y+=this.dy;this.dy<this.eProp("terminal")&&(!this.touchers("d").length&&!this._teatherHost)&&(this.dy+=this.eProp("gravity"));if(1==this.path("../../scheme").tilePointIn(this.x+4,this.y+this.prop("height"))[0]&&0==this.path("../../scheme").tilePointIn(this.x+4,this.y+this.prop("height"))[1]||1==this.path("../../scheme").tilePointIn(this.x+this.prop("width")-
4,this.y+this.prop("height"))[0]&&0==this.path("../../scheme").tilePointIn(this.x+this.prop("width")-4,this.y+this.prop("height"))[1])this.dy=0,this.snapY(!1),this._behave.onLand();if(1==this.path("../../scheme").tilePointIn(this.x+4,this.y)[0]&&0==this.path("../../scheme").tilePointIn(this.x+4,this.y)[1]||1==this.path("../../scheme").tilePointIn(this.x+this.prop("width")-4,this.y)[0]&&0==this.path("../../scheme").tilePointIn(this.x+this.prop("width")-4,this.y)[1])this.dy=0,this.snapY(!0),this._behave.onBonk();
this.dx=this.dx>this.eProp("slowdown")?this.dx-this.eProp("slowdown"):this.dx<-this.eProp("slowdown")?this.dx+this.eProp("slowdown"):0;if(!this._teatherHost||-1!==this._teatherHost[1].indexOf("u")||-1!==this._teatherHost[1].indexOf("d"))this.x+=this.dx;if(1==this.path("../../scheme").tilePointIn(this.x+this.prop("width"),this.y+4)[0]&&0==this.path("../../scheme").tilePointIn(this.x+this.prop("width"),this.y+4)[1]||1==this.path("../../scheme").tilePointIn(this.x+this.prop("width"),this.y+this.prop("height")-
4)[0]&&0==this.path("../../scheme").tilePointIn(this.x+this.prop("width"),this.y+this.prop("height")-4)[1])this.dx=0,this.snapX(!1),this._behave.onHitRight();if(1==this.path("../../scheme").tilePointIn(this.x,this.y+4)[0]&&0==this.path("../../scheme").tilePointIn(this.x,this.y+4)[1]||1==this.path("../../scheme").tilePointIn(this.x,this.y+this.prop("height")-4)[0]&&0==this.path("../../scheme").tilePointIn(this.x,this.y+this.prop("height")-4)[1])this.dx=0,this.snapX(!0),this._behave.onHitLeft();for(var a=
this._teatherClients.length-1;0<=a;a--){if(-1!==this._teatherClients[a][1].indexOf("u")&&(this._teatherClients[a][0].y=this.y-this._teatherClients[a][0].prop("height"),-1!==this._teatherClients[a][1].indexOf("X")&&(this._teatherClients[a][0].x+this._teatherClients[a][0].prop("width")<this.x||this._teatherClients[a][0].x>this.x+this.prop("width")))){this.unteather(this._teatherClients[a][0]);break}-1!==this._teatherClients[a][1].indexOf("d")&&(this._teatherClients[a][0].y=this.y+this.prop("height"));
-1!==this._teatherClients[a][1].indexOf("l")&&(this._teatherClients[a][0].x=this.x-this._teatherClients[a][0].prop("width"));-1!==this._teatherClients[a][1].indexOf("r")&&(this._teatherClients[a][0].x=this.x+this.prop("width"))}this.bookRedraw()};sgui.PlatEntity.prototype.startFrame=function(){this._behave.everyFrame();this._touchers={l:[],r:[],u:[],d:[]}};
sgui.PlatEntity.prototype.typeChange=function(a){this._type=a;this._eProps=this._events.getVar("pentity."+this._type);this.prop("tile","0,0");this.prop("src",this.eProp("img"));this._behave=new (window.pbehave[this.eProp("behaviour")])(this,this._events)};sgui.PlatEntity.prototype.collideLeft=function(a){this._touchers.r[this._touchers.r.length]=a;this._behave.onCollideLeft(a)};sgui.PlatEntity.prototype.collideRight=function(a){this._touchers.l[this._touchers.l.length]=a;this._behave.onCollideRight(a)};
sgui.PlatEntity.prototype.collideTop=function(a){this._touchers.d[this._touchers.d.length]=a;this._behave.onCollideTop(a)};sgui.PlatEntity.prototype.collideBottom=function(a){this._touchers.u[this._touchers.u.length]=a;this._behave.onCollideBottom(a)};sgui.PlatEntity.prototype.touchers=function(a){return!(a in this._touchers)?(console.warn("Unknown dir "+a+" for touching!"),[]):this._touchers[a]};
sgui.PlatEntity.prototype.teather=function(a,b){this._teatherClients[this._teatherClients.length]=[a,b];a.receiveTeather(this,b)};sgui.PlatEntity.prototype.unteather=function(a){a.receiveTeather(null,null);for(var b=this._teatherClients.length-1;0<=b;b--)this._teatherClients[b][0]==a&&this._teatherClients.splice(b,1)};sgui.PlatEntity.prototype.receiveTeather=function(a,b){this._teatherHost=a?[a,b]:null};sgui.PlatEntity.prototype.teatherClients=function(){return this._teatherClients};
sgui.PlatEntity.prototype.eProp=function(a,b){if(void 0!==b)return this._eProps[a]=b;if(this._eProps&&a in this._eProps)return this._eProps[a]};dusk.sgui.TileMap={};
sgui.TileMap=function(a,b,c){void 0!==a&&(sgui.Component.call(this,a,b,c),this._registerProp("map",this._doMap,null,["src","tile-size","sprite-size"]),this._registerPropMask("bound-l","_lbound",!0),this._registerPropMask("bound-r","_rbound",!0),this._registerPropMask("bound-u","_ubound",!0),this._registerPropMask("bound-b","_bbound",!0),this._registerPropMask("tile-size","_tsize",!0),this._registerPropMask("sprite-size","_ssize",!0),this._registerPropMask("src","_defImg",!0),this._hspacing=this._theme("tm.spacing.h",
0),this._vspacing=this._theme("tm.spacing.v",0),this.prop("width",this._events.getVar("sys.sg.width")),this.prop("height",this._events.getVar("sys.sg.height")),this._tsize=this._theme("tm.tsize",4),this._ssize=this._theme("tm.ssize",5),this._bbound=this._rbound=this._ubound=this._lbound=0,this.cols=this.rows=-1,this._defImg="",this._all=this._img=null,this._drawn=!1,this._tileBuffer=new ArrayBuffer(0),this._tiles=new Uint8Array(this._tileBuffer),this._registerDrawHandler(this._tileMapDraw))};
sgui.TileMap.prototype=new sgui.Component;sgui.TileMap.constructor=sgui.TileMap;sgui.TileMap.prototype.className="TileMap";
sgui.TileMap.prototype._doMap=function(a,b){"rows"in b||(b.rows=this._theme("tm-rows",5));"cols"in b||(b.cols=this._theme("tm-cols",5));this._img="src"in b?dusk.data.grabImage(b.src):dusk.data.grabImage(this._defImg);var c=1<<this._tsize,d=1<<this._tsize;"-1"==b.rows&&(b.rows=Math.floor(this.prop("height")/d));"-1"==b.cols&&(b.cols=Math.floor(this.prop("width")/c));this._tileBuffer=new ArrayBuffer(b.rows*b.cols<<1);this._tiles=new Uint8Array(this._tileBuffer);for(var c=b.map.split(/\s+/g),e=d=0;e<
c.length;e++)-1!==c[e].indexOf(",")&&(this._tiles[d++]=c[e].split(",")[0],this._tiles[d++]=c[e].split(",")[1]);this.rows=b.rows;this.cols=b.cols;this._all=document.createElement("canvas");this._all.width=(this.cols<<this._tsize)+this.prop("width");this._all.height=(this.rows<<this._tsize)+this.prop("height");this._all.style.imageRendering="-webkit-optimize-contrast";this.drawAll();this.setBoundsCoord(0,0,this.prop("width"),this.prop("height"))};
sgui.TileMap.prototype.drawAll=function(){this._drawn=!1;if(!this._img.complete)return!1;var a=0;this._all.getContext("2d").clearRect(0,0,this._all.width,this._all.height);for(var b=0;b<this.rows;b++)for(var c=0;c<this.cols;c++)void 0!==this._tiles[a]&&this._all.getContext("2d").drawImage(this._img,this._tiles[a]<<this._ssize,this._tiles[a+1]<<this._ssize,1<<this._ssize,1<<this._ssize,c<<this._tsize,b<<this._tsize,1<<this._tsize,1<<this._tsize),a+=2;return this._drawn=!0};
sgui.TileMap.prototype.setBoundsCoord=function(a,b,c,d){this._lbound=a;this._rbound=c;this._ubound=b;this._bbound=d;this.bookRedraw()};sgui.TileMap.prototype.setBounds=function(a,b,c,d){void 0===c&&(c=a+this.cols);void 0===d&&(d=b+this.rows);this.dec?console.warn("Decimal tilemaps have not been fully implemented!"):(this._lbound=a<<this._tsize,this._rbound=c<<this._tsize,this._ubound=b<<this._tsize,this._bbound=d<<this._tsize);this.bookRedraw()};
sgui.TileMap.prototype.tilePointIn=function(a,b,c,d){a/=1<<this._tsize;b/=1<<this._tsize;return c&&d?this.getTile(a,b):c?this.getTile(a,Math.floor(b)):d?this.getTile(Math.floor(a),b):this.getTile(Math.floor(a),Math.floor(b))};
sgui.TileMap.prototype._tileMapDraw=function(a){if(this._img){this._drawn||this.drawAll();var b=0>this._ubound?0:this._ubound,c=0>this._lbound?0:this._lbound;a.drawImage(this._all,c,b,this._rbound-this._lbound,this._bbound-this._ubound,c,b,this._rbound-this._lbound,this._bbound-this._ubound)}};
sgui.TileMap.prototype.getTile=function(a,b){if(void 0!==this._tiles[b*this.cols+a<<1])return[this._tiles[b*this.cols+a<<1],this._tiles[(b*this.cols+a<<1)+1]];console.warn("Tile "+a+","+b+" not found on "+this.comName+", wanting "+(b*this.cols+a<<1)+" and I can't find it.");return[0,0]};
sgui.TileMap.prototype.setTile=function(a,b,c,d,e){void 0!==this._tiles[b*this.cols+a<<1]?(this._tiles[b*this.cols+a<<1]=c,this._tiles[(b*this.cols+a<<1)+1]=d,e&&this.drawAll()):console.warn("Tile "+a+","+b+" not found on "+this.comName+", wanting to set"+(b*this.cols+a<<1)+" and I can't find it.")};sgui.TileMap.prototype.getRelativeTile=function(a,b){return this.getTile(a+this._lbound>>this._tsize,b+this._ubound>>this._tsize)};
sgui.TileMap.prototype.inRelativeRange=function(a,b){return 0>a+(this._lbound>>this._tsize)||a+(this._lbound>>this._tsize)>=this.cols||0>b+(this._ubound>>this._tsize)||b+(this._ubound>>this._tsize)>=this.rows?!1:!0};sgui.TileMap.prototype.tileWidth=function(){return 1<<this._tsize};sgui.TileMap.prototype.tileHeight=function(){return 1<<this._tsize};sgui.TileMap.prototype.visibleCols=function(){return Math.floor(this.prop("width")/(1<<this._tsize))};
sgui.TileMap.prototype.visibleRows=function(){return Math.floor(this.prop("height")/(1<<this._tsize))};sgui.TileMap.prototype.lookTile=function(a,b){for(var c=this.rows*this.cols<<1;0<c;c-=2)if(this._tiles[c]==a&&this._tiles[c+1]==b)return[(c>>1)%this.cols,Math.floor((c>>1)/this.cols)];return[0,0]};dusk.sgui.EditableTileMap={};sgui.EditableTileMap=function(a,b,c){void 0!==a&&(sgui.TileMap.call(this,a,b,c),this._registerPropMask("cursorColour","_cursorColour",!0),this._registerPropMask("cursorColor","_cursorColour",!0),this._registerPropMask("globalCoords","_globalCoords",!0),this._globalCoords=this._theme("etm.globalCoords",!1),this._cy=this._cx=0,this._registerDrawHandler(this._editTileMapDraw),this._registerFrameHandler(this._editTileMapFrame))};sgui.EditableTileMap.prototype=new sgui.TileMap;
sgui.EditableTileMap.constructor=sgui.EditableTileMap;sgui.EditableTileMap.prototype.className="EditableTileMap";sgui.EditableTileMap.prototype._editTileMapDraw=function(a){this._focused&&(a.strokeStyle=this.prop("cursorColour"),a.strokeRect(this._cx*this.tileWidth(),this._cy*this.tileHeight(),this.tileWidth(),this.tileHeight()))};
sgui.EditableTileMap.prototype._editTileMapFrame=function(){void 0===dusk.events.getVar("etm.x")&&dusk.events.setVar("etm.x",0);void 0===dusk.events.getVar("etm.y")&&dusk.events.setVar("etm.y",0);this._focused?(dusk.events.setVar("etm.x",this._cx),dusk.events.setVar("etm.y",this._cy)):(this._cx=dusk.events.getVar("etm.x"),this._cy=dusk.events.getVar("etm.y"))};
sgui.EditableTileMap.prototype._upAction=function(a){if(a.ctrlKey)return!0;if(a.shiftKey)return a=this.getTile(this._cx,this._cy),a[1]--,this.setTile(this._cx,this._cy,a[0],a[1],!0),this.bookRedraw(),!1;if(dusk.mods.keyboard.isKeyPressed(65))return 1<=this.prop("alpha")+0.1?this.prop("alpha",1):this.prop("alpha",this.prop("alpha")+0.1),!1;this._cy--;this.bookRedraw()};
sgui.EditableTileMap.prototype._downAction=function(a){if(a.ctrlKey)return!0;if(a.shiftKey)return a=this.getTile(this._cx,this._cy),a[1]++,this.setTile(this._cx,this._cy,a[0],a[1],!0),this.bookRedraw(),!1;if(dusk.mods.keyboard.isKeyPressed(65))return 0>=this.prop("alpha")-0.1?this.prop("alpha",0):this.prop("alpha",this.prop("alpha")-0.1),!1;this._cy++;this.bookRedraw()};
sgui.EditableTileMap.prototype._rightAction=function(a){if(a.ctrlKey)return!0;if(a.shiftKey)return a=this.getTile(this._cx,this._cy),a[0]++,this.setTile(this._cx,this._cy,a[0],a[1],!0),this.bookRedraw(),!1;if(dusk.mods.keyboard.isKeyPressed(65))return 1<=this.prop("alpha")+0.1?this.prop("alpha",1):this.prop("alpha",this.prop("alpha")+0.1),!1;this._cx++;this.bookRedraw()};
sgui.EditableTileMap.prototype._leftAction=function(a){if(a.ctrlKey)return!0;if(a.shiftKey)return a=this.getTile(this._cx,this._cy),a[0]--,this.setTile(this._cx,this._cy,a[0],a[1],!0),this.bookRedraw(),!1;if(dusk.mods.keyboard.isKeyPressed(65))return 0>=this.prop("alpha")-0.1?this.prop("alpha",0):this.prop("alpha",this.prop("alpha")-0.1),!1;this._cx--;this.bookRedraw()};dusk.sgui.PlatMain={};
sgui.PlatMain=function(a,b,c){void 0!==a&&(sgui.Group.call(this,a,b,c),this._registerFrameHandler(this._platMainFrame),this.prop("width",this._events.getVar("sys.sg.width")),this.prop("height",this._events.getVar("sys.sg.height")),this._registerPropMask("sprite-size","_ssize",!0),this._registerPropMask("tile-size","_tsize",!0),this._registerPropMask("spawn","_spawn",!0),this._registerProp("room",this._room,function(){return this._room},["spawn"]),this._tsize=this._events.getVar("plat.tsize"),this._ssize=
this._events.getVar("plat.ssize"),this._scrollSpeed=this._theme("plat.scrollSpeed",10),this._spawn=0,this._entities=[],this._room="")};sgui.PlatMain.prototype=new sgui.Group;sgui.PlatMain.constructor=sgui.PlatMain;sgui.PlatMain.prototype.className="PlatMain";
sgui.PlatMain.prototype._room=function(a,b){var c=this._events.getVar("proom."+b);events.setVar("theme.default.etm.globalcoords",!0);this.parseProps({focus:"noEdit",children:[{name:"noEdit",type:"NullCom"},{name:"back",type:"EditableTileMap",cursorColour:"#00ff00","flow-down":"over","flow-up":"scheme",src:c.backSrc,"tile-size":this._tsize,"sprite-size":this._ssize,map:{map:c.back,rows:c.rows,cols:c.cols},width:this.prop("width"),height:this.prop("height")},{name:"entities",type:"Group",children:[{name:this._events.getVar("plat.seek"),
type:"PlatEntity"}]},{name:"over",type:"EditableTileMap",cursorColour:"#ff0000","flow-down":"scheme","flow-up":"back",src:c.overSrc,"tile-size":this._tsize,"sprite-size":this._ssize,map:{map:c.over,rows:c.rows,cols:c.cols},width:this.prop("width"),height:this.prop("height")},{name:"scheme",type:"EditableTileMap",cursorColour:"#0000ff","flow-down":"back","flow-up":"over",src:"pimg/schematics.png",alpha:0,"tile-size":this._tsize,"sprite-size":this._ssize,map:{map:c.scheme,rows:c.rows,cols:c.cols,width:this.prop("width"),
height:this.prop("height")}}]});this.path("entities/"+this._events.getVar("plat.seek")).typeChange(this._events.getVar("plat.seekType"));var d=this.getComponent("scheme").lookTile(this._spawn,1);this.path("entities/"+this._events.getVar("plat.seek")).gridGo(d[0],d[1]);this._entities=[];this._entities[0]=this.path("entities/"+this._events.getVar("plat.seek"));c=c.entities;for(d=0;d<c.length;d++)this._entities[this._entities.length]=this.path("entities").getComponent(c[d].name,"PlatEntity"),this._entities[this._entities.length-
1].typeChange(c[d].type),this._entities[this._entities.length-1].gridGo(c[d].x,c[d].y);this._room=b;this.autoScroll()};
sgui.PlatMain.prototype._platMainFrame=function(){this.autoScroll();events.getVar("plat.edit")&&"noedit"==this.getFocus().comName&&this.focus("scheme");!events.getVar("plat.edit")&&"noedit"!=this.getFocus().comName&&this.focus("noEdit");for(var a=this._entities.length-1;0<=a;a--)for(var b=a;0<=b;b--)if(this._entities[a]&&this._entities[b]&&this._entities[a]!=this._entities[b]&&Math.abs(this._entities[a].x-this._entities[b].x)<this._entities[a].prop("width")&&Math.abs(this._entities[a].y-this._entities[b].y)<
this._entities[a].prop("height"))if(Math.abs(this._entities[a].x-this._entities[b].x)>Math.abs(this._entities[a].y-this._entities[b].y)){if(this._entities[a].x>this._entities[b].x?(this._entities[a].collideRight(this._entities[b]),this._entities[b].collideLeft(this._entities[a])):(this._entities[b].collideRight(this._entities[a]),this._entities[a].collideLeft(this._entities[b])),this._entities[b].eProp("solid")&&this._entities[a].eProp("solid"))if(!this._entities[b].eProp("anchor")&&!this._entities[a].eProp("anchor")){var c=
(this._entities[a].prop("width")-Math.abs(this._entities[a].x-this._entities[b].x))/2+1;if(this._entities[a].x>this._entities[b].x){if(this._entities[a].x+=c,0>this._entities[a].dx&&(this._entities[a].dx=0),this._entities[b].x-=c,0<this._entities[b].dx)this._entities[b].dx=0}else if(this._entities[a].x-=c,0<this._entities[a].dx&&(this._entities[a].dx=0),this._entities[b].x+=c,0>this._entities[b].dx)this._entities[b].dx=0}else this._entities[b].eProp("anchor")&&!this._entities[a].eProp("anchor")?(c=
this._entities[a].prop("width")-Math.abs(this._entities[a].x-this._entities[b].x),this._entities[a].x>this._entities[b].x?(this._entities[a].x+=c,0>this._entities[a].dx&&(this._entities[a].dx=0)):(this._entities[a].x-=c,0<this._entities[a].dx&&(this._entities[a].dx=0))):!this._entities[b].eProp("anchor")&&this._entities[a].eProp("anchor")&&(c=this._entities[a].prop("width")-Math.abs(this._entities[a].x-this._entities[b].x),this._entities[b].x>this._entities[a].x?(this._entities[b].x+=c,0>this._entities[b].dx&&
(this._entities[b].dx=0)):(this._entities[b].x-=c,0<this._entities[b].dx&&(this._entities[b].dx=0)))}else if(this._entities[a].y>this._entities[b].y?(this._entities[a].collideBottom(this._entities[b]),this._entities[b].collideTop(this._entities[a])):(this._entities[b].collideBottom(this._entities[a]),this._entities[a].collideTop(this._entities[b])),this._entities[b].eProp("solid")&&this._entities[a].eProp("solid"))if(!this._entities[b].eProp("anchor")&&!this._entities[a].eProp("anchor"))if(c=(this._entities[a].prop("height")-
Math.abs(this._entities[a].y-this._entities[b].y))/2+1,this._entities[a].y>this._entities[b].y){if(this._entities[a].y+=c,0>this._entities[a].dy&&(this._entities[a].dy=0),this._entities[b].y-=c,0<this._entities[b].dy)this._entities[b].dy=0}else{if(this._entities[a].y-=c,0<this._entities[a].dy&&(this._entities[a].dy=0),this._entities[b].y+=c,0>this._entities[b].dy)this._entities[b].dy=0}else this._entities[b].eProp("anchor")&&!this._entities[a].eProp("anchor")?(c=this._entities[a].prop("height")-Math.abs(this._entities[a].y-
this._entities[b].y),this._entities[a].y>this._entities[b].y?(this._entities[a].y+=c,0>this._entities[a].dy&&(this._entities[a].dy=0)):(this._entities[a].y-=c,0<this._entities[a].dy&&(this._entities[a].dy=0))):!this._entities[b].eProp("anchor")&&this._entities[a].eProp("anchor")&&(c=this._entities[a].prop("height")-Math.abs(this._entities[a].y-this._entities[b].y),this._entities[b].y>this._entities[a].y?(this._entities[b].y+=c,0>this._entities[b].dy&&(this._entities[b].dy=0)):(this._entities[b].y-=
c,0<this._entities[b].dy&&(this._entities[b].dy=0)));for(a=this._entities.length-1;0<=a;a--)this._entities[a].moveAndCollide();for(a=this._entities.length-1;0<=a;a--)this._entities[a].startFrame()};
sgui.PlatMain.prototype.autoScroll=function(){var a=events.getVar("plat.edit")?[events.getVar("etm.x")<<this._tsize,events.getVar("etm.y")<<this._tsize]:[this.path("entities/"+this._events.getVar("plat.seek")).x,this.path("entities/"+this._events.getVar("plat.seek")).y];this._container.prop("seek",a);this.getComponent("scheme").setBoundsCoord(a[0]-(this.prop("width")>>1),a[1]-(this.prop("height")>>1),a[0]+(this.prop("width")>>1),a[1]+(this.prop("height")>>1));this.getComponent("back").setBoundsCoord(a[0]-
(this.prop("width")>>1),a[1]-(this.prop("height")>>1),a[0]+(this.prop("width")>>1),a[1]+(this.prop("height")>>1));this.getComponent("over").setBoundsCoord(a[0]-(this.prop("width")>>1),a[1]-(this.prop("height")>>1),a[0]+(this.prop("width")>>1),a[1]+(this.prop("height")>>1))};sgui.PlatMain.prototype.allEntities=function(){return this._entities};dusk.mods.plat={};
dusk.mods.plat.init=function(){events.setVar("plat.seek","hero");events.setVar("plat.seektype","player");events.setVar("plat.skill.jump",!0);events.setVar("plat.skill.dubjump",!0);events.setVar("plat.skill.infinijump",!0);events.setVar("pentity.default.gravity",1.5);events.setVar("pentity.default.terminal",10);events.setVar("pentity.default.behaviour","Stayer");events.setVar("pentity.default.haccel",4);events.setVar("pentity.default.hspeed",10);events.setVar("pentity.default.jump",17);events.setVar("pentity.default.slowdown",
2);events.setVar("pentity.default.img","pimg/hero.png");events.setVar("pentity.default.solid",!0);events.setVar("pentity.default.anchor",!1);events.setVar("plat.ssize",4);events.setVar("plat.tsize",5);dusk.events.registerStartHandler(this._onStart,this);events.registerAction("plat-room",this._setRoom,this,[["room",!0,"STR"],["spawn",!0,"NUM"]])};
dusk.mods.plat._onStart=function(){events.run([{a:"listen",event:"sys-event-load",actions:[{a:"pane",active:!0,focus:"mainContainer",name:"plat-main",children:[{name:"mainContainer",focus:"main",type:"CentreScroller",width:dusk.events.getVar("sys.sg.width"),height:dusk.events.getVar("sys.sg.height"),child:{name:"main",type:"PlatMain"}}]}]}],"_plat")};
dusk.mods.plat._setRoom=function(a){if(!("room"in a))throw new dusk.errors.PropertyMissing(a.a,"room");console.log("Setting room "+a.room+".");events.run(dusk.data.grabJson("prooms/"+a.room.replace(/\-/g,"_")),dusk.events.thread);events.run([{a:"sg-path",pane:"plat-main",path:"/mainContainer/main",fade:{from:1,to:0,speed:-0.05}},{a:"sg-path",pane:"plat-main",path:"/mainContainer/main",room:a.room,spawn:a.spawn},{a:"sg-path",pane:"plat-main",path:"/mainContainer/main",fade:{from:0,to:1,speed:0.05}},
{a:"fire",event:"plat-room-load",room:a.room}],events.thread)};dusk.mods.plat.init();
