goog.addDependency("../../DuskWolf/Data.js", ["dusk.data"], ["dusk"]);
goog.addDependency("../../DuskWolf/DuskWolf.js", ["dusk"], []);
goog.addDependency("../../DuskWolf/Events.js", ["dusk.events"], ["dusk.dwc", "dusk.errors"]);
goog.addDependency("../../DuskWolf/Game.js", ["dusk.game"], ["dusk", "dusk.data", "dusk.events"]);
goog.addDependency("../../DuskWolf/Dwc.js", ["dusk.dwc"], []);
goog.addDependency("../../DuskWolf/Load.js", ["dusk.load"], ["dusk", "dusk.game"]);
goog.addDependency("../../DuskWolf/Errors.js", ["dusk.errors"], []);

goog.addDependency("../../DuskWolf/mods/IModule.js", ["dusk.mods.imod"], []);
goog.addDependency("../../DuskWolf/mods/Core.js", ["dusk.mods.core"], []);
goog.addDependency("../../DuskWolf/mods/Keyboard.js", ["dusk.mods.keyboard"], []);
goog.addDependency("../../DuskWolf/mods/LocalSaver.js", ["dusk.mods.localSaver"], []);
goog.addDependency("../../DuskWolf/mods/Math.js", ["dusk.mods.math"], []);
goog.addDependency("../../DuskWolf/mods/Net.js", ["dusk.mods.net"], []);
goog.addDependency("../../DuskWolf/mods/Plat.js", ["dusk.mods.plat"], ["dusk.mods.simpleGui", "dusk.sgui.PlatMain", "dusk.sgui.CentreScroller", "dusk.pbehave.PBehave"]);
goog.addDependency("../../DuskWolf/mods/SimpleGui.js", ["dusk.mods.simpleGui"], ["dusk.sgui.Pane"]);

goog.addDependency("../../DuskWolf/sgui/Component.js", ["dusk.sgui.Component", "dusk.sgui.NullCom"], []);
goog.addDependency("../../DuskWolf/sgui/Group.js", ["dusk.sgui.Group"], ["dusk.sgui.IContainer"]);
goog.addDependency("../../DuskWolf/sgui/IContainer.js", ["dusk.sgui.IContainer"], ["dusk.sgui.Component"]);
goog.addDependency("../../DuskWolf/sgui/Pane.js", ["dusk.sgui.Pane"], ["dusk.sgui.Group"]);
goog.addDependency("../../DuskWolf/sgui/CentreScroller.js", ["dusk.sgui.CentreScroller"], ["dusk.sgui.Single"]);
goog.addDependency("../../DuskWolf/sgui/DecimalTile.js", ["dusk.sgui.DecimalTile"], []);
goog.addDependency("../../DuskWolf/sgui/DirListener.js", ["dusk.sgui.DirListener"], ["dusk.sgui.Single"]);
goog.addDependency("../../DuskWolf/sgui/EditableTileMap.js", ["dusk.sgui.EditableTileMap"], ["dusk.sgui.TileMap"]);
goog.addDependency("../../DuskWolf/sgui/FocusChecker.js", ["dusk.sgui.FocusChecker"], ["dusk.sgui.Image"]);
goog.addDependency("../../DuskWolf/sgui/Grid.js", ["dusk.sgui.Grid"], ["dusk.sgui.Group"]);
goog.addDependency("../../DuskWolf/sgui/Image.js", ["dusk.sgui.Image"], []);
goog.addDependency("../../DuskWolf/sgui/PlatEntity.js", ["dusk.sgui.PlatEntity"], ["dusk.sgui.Tile"]);
goog.addDependency("../../DuskWolf/sgui/PlatMain.js", ["dusk.sgui.PlatMain"], ["dusk.sgui.Group", "dusk.sgui.PlatEntity", "dusk.sgui.EditableTileMap", "dusk.sgui.EntityGroup"]);
goog.addDependency("../../DuskWolf/sgui/Rect.js", ["dusk.sgui.Rect"], []);
goog.addDependency("../../DuskWolf/sgui/Saybox.js", ["dusk.sgui.Saybox"], ["dusk.sgui.VMenu", "dusk.sgui.Text"]);
goog.addDependency("../../DuskWolf/sgui/Single.js", ["dusk.sgui.Single"], ["dusk.sgui.IContainer"]);
goog.addDependency("../../DuskWolf/sgui/Text.js", ["dusk.sgui.Label", "dusk.sgui.Text", "dusk.sgui.TextBox"], []);
goog.addDependency("../../DuskWolf/sgui/Tile.js", ["dusk.sgui.Tile"], []);
goog.addDependency("../../DuskWolf/sgui/TileMap.js", ["dusk.sgui.TileMap"], []);
goog.addDependency("../../DuskWolf/sgui/EntityGroup.js", ["dusk.sgui.EntityGroup"], ["dusk.sgui.Group"]);

goog.addDependency("../../DuskWolf/platBehaviours/PBehave.js", ["dusk.pbehave.PBehave"], []);
goog.addDependency("../../DuskWolf/platBehaviours/BackForth.js", ["dusk.pbehave.BackForth"], []);
goog.addDependency("../../DuskWolf/platBehaviours/Controlled.js", ["dusk.pbehave.Controlled"], []);
goog.addDependency("../../DuskWolf/platBehaviours/Fade.js", ["dusk.pbehave.Fade"], []);
goog.addDependency("../../DuskWolf/platBehaviours/Fall.js", ["dusk.pbehave.Fall"], []);
goog.addDependency("../../DuskWolf/platBehaviours/Push.js", ["dusk.pbehave.Push"], []);
