#!/usr/bin/python

# Concatinates all the files of a namespace into one file, doesn't load as expected, though

# > catFile.py

import sys
import os
import posixpath
import re
import json
import dwload

sources = raw_input("Please enter namespace files seperated with space: ").split(" ")
for s in sources:
	dwload.importList(s)

packages = raw_input("Please enter package names seperated with space: ").split(" ")

outfile = file(raw_input("Please enter output file name: "), "w")

outfile.write("// Generated by catFile.py\n")
outfile.write('"use strict"\n')

ls = dwload.LoadState();

def onFileProvide(filename, remote):
	if remote:
		return
	
	outfile.write("\n// ++++ "+filename+"\n")
	
	infile = file(filename)
	
	outfile.write(infile.read())

ls.onFileProvide = onFileProvide
ls.skipUnknown = True
ls.skipLoad = True

for p in packages:
	ls.importPackage(p)
